Repository eclipse-sw360/sw360, pull requests merged in 2018-07, with the labels that each got.

#316 fix(licenseinfo): Update merge handling for licenseInfo objects
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/OutputGenerator.java
Labels: needs code review, needs test

#323 feat(search): Improve lucene search logic and handling of results
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/VendorSearchHandler.java
  backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorHandler.java
  build-configuration/resources/couchdb.properties
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/datatables/PaginationParser.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/datatables/data/PaginationParameters.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/webapp/html/components/view.jsp
  frontend/sw360-portlet/src/main/webapp/html/projects/view.jsp
  frontend/sw360-portlet/src/main/webapp/html/utils/includes/searchReleases.jsp
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/DatabaseSettings.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
  libraries/lib-datahandler/src/main/thrift/vendors.thrift
Labels: needs test

#300 fix(component): Do not update component properties if they are not in request
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortletUtils.java
Labels: WIP
