Repository eclipse-sw360/sw360, pull requests merged in 2019-02, with the labels that each got.

#448 chore(thrift): build thrift with `--without-java` flag
  .travis.yml
  scripts/compileWithDocker.sh
  scripts/install-thrift.sh
Labels: needs code review, needs test

#440 fix(auth): fix screen name auth problem
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/UserRepository.java
  rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/Sw360AuthenticationProvider.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/Sw360UserService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ComponentTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ProjectTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ReleaseTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/AttachmentSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VulnerabilitySpecTest.java
Labels: needs test

#452 feat(license-info): Add version string to file name
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Labels: needs test

#460 fix(vul-scheduler): fixed an issue where vulnerabilities were stored in the wrong db
  backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasink/VulnerabilityConnector.java
  backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/VulnerabilityHandler.java
  backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/db/VulnerabilityDatabaseHandler.java
Labels: needs code review, needs test

#471 fix(scripts): add missing dependency to scripts/install-thrift.sh
  scripts/install-thrift.sh
Labels: good first issue, needs test

#439 chores(quick-deploy): add quick deploy for portlet
  backend/svc/pom.xml
  frontend/sw360-portlet/pom.xml
  frontend/sw360-portlet/src/main/webapp/META-INF/context.xml
Labels: needs test

#462 feat(attachment-usage): Restrict modification of the attachment usage
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/webapp/html/projects/includes/attachmentUsages.jspf
  frontend/sw360-portlet/src/main/webapp/html/projects/includes/attachmentUsagesRows.jspf
  frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/vulnerabilities.jspf
Labels: needs test

#467 feat(UI:PageTitle): Show selected Project/Component Name in Browser Tab
  frontend/sw360-portlet/src/main/webapp/html/components/edit.jsp
  frontend/sw360-portlet/src/main/webapp/html/components/editRelease.jsp
  frontend/sw360-portlet/src/main/webapp/html/components/includes/components/detailOverview.jspf
  frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/detailOverview.jspf
  frontend/sw360-portlet/src/main/webapp/html/projects/edit.jsp
  frontend/sw360-portlet/src/main/webapp/html/projects/includes/detailOverview.jspf
Labels: needs test

#438 chore(licenseinfo): Reporting Component Subsection
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxUtils.java
  backend/src/src-licenseinfo/src/main/resources/templateReport.docx
  libraries/lib-datahandler/src/main/thrift/licenseinfo.thrift
Labels: needs test

#458 feat(duplicates): added support to prevent duplicate projects/components/releases
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src-common/src/test/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandlerTest.java
  backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  libraries/lib-datahandler/src/main/thrift/sw360.thrift
Labels: increases minor version
