Repository eclipse-sw360/sw360, pull requests merged in 2019-11, with the labels that each got.

#706 fix(component): incorrect release edit link in component edit page
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/edit.jsp
Labels: needs code review, needs general test

#712 fix(projectUI): NPE in ProjectDatabaseHandler.setReleaseRelations
  backend/src-common/src/main/java/org/eclipse/sw360/common/utils/BackendUtils.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
Labels: needs code review

#709 fix(project): prevent cyclic link in linked projects
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
Labels: needs code review, needs general test

#716 fix(LicenseInfo): NPE in ProjectPortlet.prepareLicenseInfo and downloadLicenseInfo
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
Labels: ready

#687 fix(rest): License information generation based on attachment usages from rest
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/licenseinfo/Sw360LicenseInfoService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
Labels: needs code review, needs general test

#666 feat(Project-UI) License Obligation tracker at Project Level
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src-common/src/test/java/org/eclipse/sw360/components/summary/ProjectSummaryTest.java
  backend/src/src-licenseinfo/pom.xml
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/AbstractCLIParser.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/CLIParser.java
  backend/src/src-licenseinfo/src/main/resources/templateReport.docx
  backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/CLIParserTest.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/detail.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/editObligations.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/linkedObligations.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsByReleases.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/viewByObligations.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/bridges/datatables.js
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/datatables-renderer.js
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/utils/render.js
  frontend/sw360-portlet/src/main/resources/sw360.properties
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
  libraries/lib-datahandler/src/main/thrift/licenseinfo.thrift
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
Labels: needs general test

#714 feat(REST): linked release hierarchy is included in the response
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
Labels: needs code review, needs general test

#608 fix(Components): Fix naming component error (component's name contains only space characters)
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  libraries/lib-datahandler/src/main/thrift/sw360.thrift
Labels: needs clarification, needs code review, needs general test

#721 fix(projectUI): NPE in SW360Utils.getApprovedClxAttachmentForRelease
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/detail.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/linkedObligations.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsByReleases.jspf
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
Labels: needs code review

#718 fix(businessrules): NPE in clearingStateSummaryComputer
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/businessrules/ReleaseClearingStateSummaryComputer.java
Labels: needs code review, needs general test

#731 fix(ui): Added missing tooltip
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/todos/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/ajax/linkedProjectsAjax.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleasesAjax.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/editAdditionalData.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/editExternalIds.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/mapEdit.jspf
Labels: needs code review, needs general test

#720 feat(rest): get attachmentUsages for a project
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: needs code review, needs general test

#728 fix(ProjectUI): Obligation view for changes in linked release attachment
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/AbstractCLIParser.java
  backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandlerTest.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/detail.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/editObligations.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/linkedObligations.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsByReleases.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/viewByObligations.jspf
  frontend/sw360-portlet/src/main/resources/sw360.properties
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
  libraries/lib-datahandler/src/main/thrift/licenseinfo.thrift
  libraries/lib-datahandler/src/main/thrift/projects.thrift
Labels: needs code review, needs general test

#717 fix(rest): Error getting component/project with unknown creator
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Labels: ready
