Repository eclipse-sw360/sw360, pull requests merged in 2019-09, with the labels that each got.

#654 fix(EditRelease UI): Removed duplicate field 'Licenses' from edit release
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/editReleaseInformation.jspf
Labels: ready

#604 feat(license-disclosure): External Ids incorporated in the license disclosure
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxUtils.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/OutputGenerator.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/TextGenerator.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGenerator.java
  backend/src/src-licenseinfo/src/main/resources/templateFrontpageContent.docx
  backend/src/src-licenseinfo/src/main/resources/textLicenseInfoFile.vm
  backend/src/src-licenseinfo/src/main/resources/xhtmlLicenseInfoFile.vm
  backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGeneratorTest.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayOutputFormats.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/licenseInfo.jsp
  libraries/lib-datahandler/src/main/thrift/licenseinfo.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/licenseinfo/Sw360LicenseInfoService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: needs code review, needs general test

#648 fix(rest): Fixed get component API having default vendor id as empty
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
Labels: needs code review, needs general test

#634 fix(REST-API): Corrected download link for attachments
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/AttachmentController.java
Labels: needs code review, needs general test

#632 Fix(Project UI): Fixed Lic Info Header & Obligation when duplicating Project
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administrationEdit.jspf
Labels: ready

#613 fix(Rest-API): Corrected 'createdBy' field value for Project and Component
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ComponentTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready

#644 fix(DownloadLicenseInfo): Corrected license selection based on attachment selection on attachmentusage
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
Labels: ready

#601 feat(License Disclosure): Change order of listed items in disclosure documents
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/OutputGenerator.java
  backend/src/src-licenseinfo/src/main/resources/textLicenseInfoFile.vm
  backend/src/src-licenseinfo/src/main/resources/xhtmlLicenseInfoFile.vm
Labels: ready

#640 fix(merge): Some fields were not merged
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
Labels: needs clarification, needs general test

#662 chores(config): Fix friendly URL for license page
  frontend/configuration/Private_Pages.lar
Labels: ready

#667 chores(merge): Retain owner as moderator
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  frontend/liferay-theme/src/main/webapp/css/portlet/_components.scss
  frontend/sw360-portlet/src/main/resources/META-INF/resources/css/portlets/components/_merge.scss
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeComponent.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/mergeWizard.js
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/sw360Wizard.js
Labels: needs code review

#671 fix(REST Project) : Fixed error response for create project from rest
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
Labels: ready

#675 fix(licenseDisclosure): Added acknowledgements in TEXT and DOCX format
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  backend/src/src-licenseinfo/src/main/resources/textLicenseInfoFile.vm
Labels: needs code review, needs general test

#665 feature(table-filter): add filter box, fix print
  frontend/liferay-theme/src/main/webapp/css/sw360/components/_table.scss
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/databaseSanitation/duplicatesAjax.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/clearingStatus.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/vulnerabilities.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeComponent.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/ecc/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailRisks.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/eccStatus.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/vulnerabilities.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/usingProjectsTable.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/vulnerabilities/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/bridges/datatables.js
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/datatables-renderer.js
Labels: needs code review, needs general test

#638 fix(Component UI): Fixed SPDX License import functionality for XML CLI files
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/clearingDetails.jspf
Labels: ready

#669 fix(LicenseDisclosureDocument): Ordering and formating license disclosure document.
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/OutputGenerator.java
  backend/src/src-licenseinfo/src/main/resources/textLicenseInfoFile.vm
  backend/src/src-licenseinfo/src/main/resources/xhtmlLicenseInfoFile.vm
Labels: needs code review, needs general test

#681 fix(vendor): fix view name used when editing vendors
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseRepository.java
Labels: needs code review, needs general test
