Repository eclipse-sw360/sw360, pull requests merged in 2019-07, with the labels that each got.

#570 feat(Rest-Project) : Added possibility to update project from rest endpoint.
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: needs general test

#577 feat(rest): Whitelist fields in REST API response
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: needs code review, needs general test

#510 fix(wsimport): small fixes, refactoring and improvements
  backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/entitytranslation/WsLibraryToSw360ComponentTranslator.java
  backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/entitytranslation/WsLibraryToSw360ReleaseTranslator.java
  backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/entitytranslation/WsLicenseToSw360LicenseTranslator.java
  backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/rest/WsImportService.java
  backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/rest/WsRestClient.java
  backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/thrift/ThriftUploader.java
  backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/utility/TranslationConstants.java
Labels: needs special test

#574 feat(attachment-usages): Take over the attachment usages from the original project.
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/webapp/html/projects/edit.jsp
Labels: needs code review

#580 fix(rest): Download licenseinfo file rest endpoint.
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/licenseinfo/Sw360LicenseInfoService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: needs code review, needs general test

#540 feat(Projects): Added new field "domain" to project summary
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/resources/sw360.properties
  frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/basicInfo.jspf
  frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/summary.jspf
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: increases minor version, needs code review, needs general test

#517 feat(licenses): adding support for project-only obligations
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/LicenseHandler.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
  frontend/configuration/PrivatePages.lar
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/TodoPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/CompareTodos.java
  frontend/sw360-portlet/src/main/webapp/WEB-INF/liferay-display.xml
  frontend/sw360-portlet/src/main/webapp/WEB-INF/liferay-portlet.xml
  frontend/sw360-portlet/src/main/webapp/WEB-INF/portlet.xml
  frontend/sw360-portlet/src/main/webapp/html/admin/todos/add.jsp
  frontend/sw360-portlet/src/main/webapp/html/admin/todos/view.jsp
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/LicsExporter.java
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/utils/ConvertRecord.java
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/utils/TypeMappings.java
  libraries/exporters/src/test/java/org/eclipse/sw360/exporter/utils/ConvertRecordTest.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftValidate.java
  libraries/lib-datahandler/src/main/thrift/licenses.thrift
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  libraries/lib-datahandler/src/main/thrift/sw360.thrift
Labels: increases minor version

#526 fix(report): corrections to report
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  backend/src/src-licenseinfo/src/main/resources/templateReport.docx
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/webapp/html/components/editRelease.jsp
  frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseInformation.jspf
  libraries/lib-datahandler/src/main/thrift/components.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: increases minor version, needs general test

#587 feat(todoMigration): migration script for todos
  scripts/migrations/007_add_submitters_usergroup_to_moderation_request.py
  scripts/migrations/008_add_component_type_to_moderation_requests.py
  scripts/migrations/009_overwrite_release_name_with_component_name.py
  scripts/migrations/010_repair_missing_vendorId_links_in_releases.py
  scripts/migrations/012_migrate_todoid_to_title.py
  scripts/migrations/README.md
Labels: increases major version, needs code review, needs general test

#593 fix(cve-search): disable tests by assume statement and refactor
  backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasource/CveSearchApiImpl.java
  backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasource/CveSearchGuesser.java
  backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasource/json/CveSearchJsonParser.java
  backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasource/json/ListCveSearchJsonParser.java
  backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasource/json/SingleCveSearchJsonParser.java
  backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/TestWithCveSearchConnection.java
  backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/datasource/CveSearchApiImplTest.java
  backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/datasource/CveSearchGuesserTest.java
  backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/datasource/CveSearchWrapperTest.java
  backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/datasource/json/CveSearchJsonParserTest.java
  backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/entitytranslation/CveSearchDataTranslatorTest.java
Labels: needs code review

#583 Add additionalData maps to releases, components, projects and licenses
  backend/src-common/src/test/java/org/eclipse/sw360/components/summary/ProjectSummaryTest.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ComponentModerationRequestGenerator.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ProjectModerationRequestGenerator.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ReleaseModerationRequestGenerator.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
  frontend/sw360-portlet/src/main/webapp/html/components/edit.jsp
  frontend/sw360-portlet/src/main/webapp/html/components/editRelease.jsp
  frontend/sw360-portlet/src/main/webapp/html/components/includes/components/summary.jspf
  frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/summaryRelease.jspf
  frontend/sw360-portlet/src/main/webapp/html/components/mergeComponent.jsp
  frontend/sw360-portlet/src/main/webapp/html/projects/edit.jsp
  frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/summary.jspf
  frontend/sw360-portlet/src/main/webapp/html/utils/includes/editAdditionalData.jsp
  frontend/sw360-portlet/src/main/webapp/html/utils/includes/editExternalIds.jsp
  frontend/sw360-portlet/src/main/webapp/js/modules/mergeWizard.js
  libraries/lib-datahandler/src/main/thrift/components.thrift
  libraries/lib-datahandler/src/main/thrift/licenses.thrift
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: increases minor version

#568 fix(Project): Only users with Admin access should be allowed to edit a closed project
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/webapp/css/sw360.css
  frontend/sw360-portlet/src/main/webapp/html/projects/detail.jsp
  frontend/sw360-portlet/src/main/webapp/html/projects/view.jsp
  libraries/lib-datahandler/src/main/thrift/sw360.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
Labels: needs general test

#598 fix(user export): fix Nullpointer Exception on user export
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/UserPortlet.java
Labels: needs special test
