Repository eclipse-sw360/sw360, pull requests merged in 2019-03, with the labels that each got.

#457 feat(UI-Project):Jump to edit release from ProjectDetails
  frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/clearingStatus.jspf
Labels: needs test

#473 fix(UI-Release): UI error on duplicate release creation
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
Labels: needs general test

#469 fix(ReleaseLink): Remove self link from LinkedReleases hierarchy
  backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
Labels: needs general test

#476 feat(search-dialog): improved multi item search dialog
  frontend/sw360-portlet/src/main/webapp/js/utils/includes/searchAndSelectIds.js
Labels: needs general test

#433 chore(licenseinfo): Reporting Improvements Part 2 #433
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/OutputGenerator.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/TextGenerator.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGenerator.java
  backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGeneratorTest.java
  backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGeneratorTest.java
Labels: WIP
