Repository eclipse-sw360/sw360, pull requests merged in 2019-04, with the labels that each got.

#490 feat(default vendor): added possibility to save a default vendor for components
  backend/src-common/src/main/java/org/eclipse/sw360/components/summary/ComponentSummary.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/VendorRepository.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayVendorEdit.java
  frontend/sw360-portlet/src/main/webapp/WEB-INF/customTags.tld
  frontend/sw360-portlet/src/main/webapp/html/admin/bulkReleaseEdit/view.jsp
  frontend/sw360-portlet/src/main/webapp/html/components/includes/components/editBasicInfo.jspf
  frontend/sw360-portlet/src/main/webapp/html/components/includes/components/summary.jspf
  frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseInformation.jspf
  frontend/sw360-portlet/src/main/webapp/html/components/mergeComponent.jsp
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftValidate.java
  libraries/lib-datahandler/src/main/thrift/components.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
Labels: increases minor version, needs general test

#470 fix(attachment): Multiple attachment upload stall issue
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/AttachmentPortletUtils.java
  libraries/commonIO/src/main/java/org/eclipse/sw360/commonIO/AttachmentFrontendUtils.java
Labels: needs clarification

#501 fix(ui): MyComponents and MyProjects does not list in Home page if email is changed
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/MyComponentsPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/MyProjectsPortlet.java
Labels: needs general test

#461 fix(Attachments-UI):Restrict from duplicate attachment upload
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/AttachmentConnector.java
  libraries/lib-datahandler/src/main/thrift/sw360.thrift
Labels: increases minor version, needs general test

#491 feat(codescoop): osman integration
  backend/src/pom.xml
  backend/src/src-codescoop/pom.xml
  backend/src/src-codescoop/src/main/java/org/eclipse/sw360/codescoop/CodescoopConfig.java
  backend/src/src-codescoop/src/main/java/org/eclipse/sw360/codescoop/CodescoopHandler.java
  backend/src/src-codescoop/src/main/java/org/eclipse/sw360/codescoop/CodescoopServlet.java
  backend/src/src-codescoop/src/main/java/org/eclipse/sw360/codescoop/CodescoopSpringServlet.java
  backend/src/src-codescoop/src/main/java/org/eclipse/sw360/codescoop/ModelTranslator.java
  backend/src/src-codescoop/src/main/resources/codescoop.properties
  backend/svc/pom.xml
  backend/svc/svc-codescoop/pom.xml
  backend/svc/svc-codescoop/src/main/webapp/WEB-INF/web.xml
  backend/svc/svc-codescoop/src/main/webapp/index.jsp
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/resources/sw360.properties
  frontend/sw360-portlet/src/main/webapp/html/components/detail.jsp
  frontend/sw360-portlet/src/main/webapp/html/components/edit.jsp
  frontend/sw360-portlet/src/main/webapp/html/components/editRelease.jsp
  frontend/sw360-portlet/src/main/webapp/html/components/includes/components/clearingStatus.jspf
  frontend/sw360-portlet/src/main/webapp/html/components/includes/components/editBasicInfo.jspf
  frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseInformation.jspf
  frontend/sw360-portlet/src/main/webapp/html/components/view.jsp
  frontend/sw360-portlet/src/main/webapp/js/modules/codeScoop.js
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftClients.java
  libraries/lib-datahandler/src/main/thrift/codescoop.thrift
Labels: needs code review, needs general test
