Repository eclipse-sw360/sw360, pull requests merged in 2019-12, with the labels that each got.

#732 fix(ProjectUI): Added options to generate ReadmeOSS for main project only or main project with subprojects.
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/linkedProjects.jspf
Labels: ready

#738 feat(REST): Added parameter to GET project by Group and Tag
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: needs code review, needs general test

#723 feat(licenseinfo): Added filter to exclude releases based on selected relationship
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseRelationsUsageRepository.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  backend/src/src-licenseinfo/src/main/resources/textLicenseInfoFile.vm
  backend/src/src-licenseinfo/src/main/resources/xhtmlLicenseInfoFile.vm
  backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentSelectTable.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/licenseInfo.jsp
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftUtils.java
  libraries/lib-datahandler/src/main/thrift/projects.thrift
Labels: ready

#730 feat(HomePageUI): Listing of MyProjects is made configurable
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
  backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
  backend/src/src-projects/src/test/java/org/eclipse/sw360/projects/ProjectHandlerTest.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/MyProjectsPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/homepage/myprojects/view.jsp
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  libraries/lib-datahandler/src/main/thrift/users.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
Labels: needs general test

#743 feat(fossology-pull-report): Pull already generated report from the fossology
  backend/src/src-fossology/src/main/java/org/eclipse/sw360/fossology/FossologyHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/FossologyAwarePortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/fossologyClearing.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/utils/includes/fossologyClearing.js
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
  libraries/lib-datahandler/src/main/thrift/fossology.thrift
Labels: needs code review, needs general test

#741 feat(WelcomePageUI): display configurable content for guidelines on welcome page
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/signup/SignupPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/welcome/WelcomePortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/homepage/signup/success.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/homepage/signup/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/homepage/welcome/view.jsp
  frontend/sw360-portlet/src/main/resources/welcomePageGuideline.html
Labels: has merge conflicts

#740 feat(REST): Add parameter to GET release by name
  rest/resource-server/src/docs/asciidoc/releases.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: needs code review, needs general test

#745 fix(licenseinfo): White page while downloading license disclosure
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/AttachmentPortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  libraries/commonIO/src/main/java/org/eclipse/sw360/commonIO/AttachmentFrontendUtils.java
Labels: needs code review, needs general test

#734 feat(ProjectMigration): script to migrate a project field to new value
  scripts/utilities/001_update_project_field_value.py
  scripts/utilities/README.md
Labels: needs code review, needs general test
