Repository eclipse-sw360/sw360, pull requests merged in 2019-10, with the labels that each got.

#683 fix(components): Recompute aggrated fields on save
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
Labels: ready

#663 fix(merge): fix update conflict on component merge
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  frontend/liferay-theme/src/main/webapp/css/_custom.scss
  frontend/liferay-theme/src/main/webapp/css/sw360/_sw360.scss
  frontend/liferay-theme/src/main/webapp/css/sw360/components/_merge.scss
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/css/components/_merge.scss
  frontend/sw360-portlet/src/main/resources/META-INF/resources/css/main.scss
  frontend/sw360-portlet/src/main/resources/META-INF/resources/css/portlets/components/_merge.scss
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/editReleaseInformation.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeComponent.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/button.js
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/mergeWizard.js
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/sw360Wizard.js
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/DatabaseConnector.java
Labels: needs code review

#685 fix(Rest-Component): Corrected components by type rest end point
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
Labels: needs code review, needs general test

#697 fix(links): Fixed the incorrect links
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentUsagesRows.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedProjectsRows.jspf
Labels: ready

#690 feat(Authorization): Added support to read keystore from central configuration
  rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/Sw360AuthorizationServerConfiguration.java
  rest/authorization-server/src/main/resources/application.yml
Labels: ready

#547 feat(Projects): enabled Project/Release mainline state change only for clearing admins
  backend/src-common/src/main/java/org/eclipse/sw360/common/utils/BackendUtils.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/mail/MailUtil.java
  backend/src-common/src/main/resources/sw360.properties
  backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
  backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
  backend/src/src-projects/src/test/java/org/eclipse/sw360/projects/ProjectHandlerTest.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/editRelease.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/editReleaseInformation.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleasesAjax.jsp
Labels: needs code review, needs general test

#677 fix(Componnet): ComponentType field should be mandatory
  backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
  backend/src/src-components/src/test/java/org/eclipse/sw360/components/ComponentHandlerTest.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/editBasicInfo.jspf
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
Labels: needs general test

#692 feat(rest): Added support to upload role category fields while creating project
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: needs general test

#698 fix(Project/Admin): Set to default text feature is not working correctly for Obligation
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administrationEdit.jspf
Labels: needs code review, needs general test

#700 fix(REST): added support for createdComment field for uploadAttachements
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
Labels: needs code review, needs general test

#680 feature(merge): add wizard for merging vendors
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentRepository.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseRepository.java
  backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
  backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorDatabaseHandler.java
  backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/VendorPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/vendors/mergeVendor.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/vendors/view.jsp
  libraries/lib-datahandler/src/main/thrift/components.thrift
  libraries/lib-datahandler/src/main/thrift/vendors.thrift
Labels: needs code review

#701 feat(moderation): Moderation requests to all clearing admin irrespective of their BU
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
Labels: needs code review, needs general test

#705 feat(Rest): New end points for project/component/release usage summary
  rest/resource-server/src/docs/asciidoc/components.adoc
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/docs/asciidoc/releases.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: ready

#564 Fix(Project UI): Removed 'Unknown' from Project Clearing Team dropdown
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administrationEdit.jspf
  frontend/sw360-portlet/src/main/resources/sw360.properties
Labels: ready
