Repository eclipse-sw360/sw360, pull requests merged in 2020-07, with the labels that each got.

#908 fix(escapeXML): Added missing escapeXML ,to prevent js script execution and rendering break due to single or double qoutes
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayCollection.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayMap.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/TagUtils.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/changelogs/elementView.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/editRelease.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/clearingStatus.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeComponent.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeRelease.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/splitComponent.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailText.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/clearing/clearingRequest.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/components/delete.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/includes/moderationHeader.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/projects/delete.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/releases/delete.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingRequest.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligations.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsEdit.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/searchReleases.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/usingComponentsTable.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/usingProjectsTable.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/mergeWizard.js
Labels: ready

#903 feat(CRUI): Modifications in Clearing Request table in moderation tab
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src-common/src/main/resources/NewClearingRequestEmailTemplate.html
  backend/src-common/src/main/resources/UpdateClearingRequestEmailTemplate.html
  backend/src-common/src/main/resources/UpdateProjectWithCREmailTemplate.html
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/clearing/clearingRequest.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingRequest.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/utils/render.js
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
Labels: ready

#912 feat(ui): Generate clearing report button replacement
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayOutputFormats.java
  frontend/sw360-portlet/src/main/resources/META-INF/customTags.tld
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/linkedObligations.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/licenseInfo.jsp
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
Labels: ready

#920 feat(EditProjectUI): Release table in edit project page should be sorted and omit vendor name
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/LinkedReleasesAndProjectsAwarePortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleasesAjax.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/linkedReleasesEdit.jspf
Labels: ready

#921 feat(REST): Whitelisting field in REST API response
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ClearingRequestRepository.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready

#905 chore(Portlet): Rename Moderation portlet to Requests
  frontend/configuration/Private_Pages.lar
Labels: ready

#890 feat(ExternalIds):Support multi-externalId Values of same externalId key in Project, Component, and Release page
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentRepository.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseRepository.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayMapOfExternalIdsString.java
  frontend/sw360-portlet/src/main/resources/META-INF/customTags.tld
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/summary.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/summaryRelease.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/summary.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/editExternalIds.jsp
  pom.xml
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
  scripts/migrations/019_update_byExternalIds_component_view.py
  scripts/migrations/020_update_byExternalIds_release_view.py
  scripts/migrations/021_update_byexternalids_project_view.py
  scripts/migrations/README.md
Labels: needs code review, needs general test

#917 feat(ComponentUI): Added new filters in Advance search
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentSearchHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
  libraries/lib-datahandler/src/main/thrift/sw360.thrift
Labels: ready

#887 feat(project-report): Layout and content update in project report
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/entitlement/LicenseModerator.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  backend/src/src-licenseinfo/src/main/resources/templateReport.docx
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/LicenseHandler.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/ObligationRepository.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/TodoRepository.java
  backend/src/src-licenses/src/test/java/org/eclipse/sw360/licenses/LicenseHandlerTest.java
  backend/src/src-licenses/src/test/java/org/eclipse/sw360/licenses/TestLicenseClient.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/LicenseModerationRequestGenerator.java
  frontend/configuration/Private_Pages.lar
  frontend/liferay-theme/src/main/webapp/css/sw360/components/_typeicon.scss
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/TodoPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/licenses/LicensesPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/CompareTodos.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/css/components/_table.scss
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/licenseAdmin/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/add.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/detail.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailAddTodo.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailTodos.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/licenses/merge.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administration.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administrationEdit.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/search/view.jsp
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/LicsExporter.java
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/utils/ConvertRecord.java
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/utils/LicsArchive.java
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/utils/TypeMappings.java
  libraries/exporters/src/test/java/org/eclipse/sw360/exporter/utils/ConvertRecordTest.java
  libraries/importers/src/main/java/org/eclipse/sw360/importer/LicsImporter.java
  libraries/importers/src/main/resources/csvfiles.properties
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftUtils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftValidate.java
  libraries/lib-datahandler/src/main/thrift/licenses.thrift
  libraries/lib-datahandler/src/main/thrift/moderation.thrift
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  scripts/migrations/022_migrate_todo_to_obligation.py
  scripts/migrations/README.md
Labels: needs general test

#925 feat(ProjectUI):Added Expand/Collapse All and Search in AttachmentUsageTable
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentUsages.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentUsagesRows.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
Labels: ready

#934 fix(license): Fixed the license loading issue
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailTodos.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administration.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administrationEdit.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
Labels: needs code review, needs general test
