Repository eclipse-sw360/sw360, pull requests merged in 2020-06, with the labels that each got.

#889 fix(MigrationScript): Update releases with empty clearingState to default value - NEW_CLEARING
  scripts/migrations/017_update_empty_release_clearing_state_to_default_value.py
  scripts/migrations/README.md
Labels: ready

#876 feat(ProjectUI):Add Clearing Request button in project Details page
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingRequest.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/validation.js
Labels: ready

#882 feat(SplitComponentUI): Split Component data like releases and attachments from Source Component to Target Component
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/splitComponent.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/mergeWizard.js
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/lib-datahandler/src/main/thrift/changelogs.thrift
  libraries/lib-datahandler/src/main/thrift/components.thrift
Labels: ready

#874 feat(REST): Added new allDetails Parameter to List Projects and List Releases API to fetch records with all details.
  backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
  libraries/lib-datahandler/src/main/thrift/components.thrift
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/docs/asciidoc/releases.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ProjectTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: ready

#880 feat(CRView): Clearing Request Comments enhancements.
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortletUtils.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/clearing/clearingRequest.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingRequest.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  scripts/migrations/018_remove_unwanted_field_from_clearing_request.py
  scripts/migrations/README.md
Labels: increases major version, ready

#900 feat(ui/search): search release using id while linking it to project
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseSearchHandler.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/searchReleasesAjax.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/searchReleases.jsp
Labels: ready

#910 fix(ProjectModeration): Fixed isWriteActionAllowedOnProject check for project update
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/entitlement/ProjectModerator.java
Labels: needs code review, needs general test
