Repository eclipse-sw360/sw360, pull requests merged in 2020-09, with the labels that each got.

#966 fix(license): Fixed the NullPointerException and addressed code duplication
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/ImportExportPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/LicenseAdminPortlet.java
Labels: needs code review, needs general test

#951 fix(ui): Fixed download license disclosure error upon selection of missing attchmnt
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentDatabaseHandler.java
  backend/src/src-attachments/src/main/java/org/eclipse/sw360/attachments/AttachmentHandler.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/licenseInfo.jsp
  libraries/lib-datahandler/src/main/thrift/attachments.thrift
Labels: needs rework

#955 fix(ui): Prevent resubmission of form for Project, Component, Vendor, Moderation inorder to prevent loss of data.
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/vendors/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/utils/link.js
Labels: ready

#969 fix(byExternalIdView): Fixed the byExternalIds view not working if the value is number.
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentRepository.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseRepository.java
  scripts/migrations/019_update_byExternalIds_component_view.py
  scripts/migrations/020_update_byExternalIds_release_view.py
  scripts/migrations/021_update_byexternalids_project_view.py
Labels: needs code review, needs general test

#974 fix(resource-server): Resolve logback conflict.
  rest/resource-server/pom.xml
Labels: ready

#939 chore(script): Added a script to uninstall the current thrift version.
  scripts/install-thrift.sh
Labels: needs general test

#983 feat(ObligationDataModel): Changes in Obligation data model
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/entitlement/LicenseModerator.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/LicenseHandler.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/TodoRepository.java
  backend/src/src-licenses/src/test/java/org/eclipse/sw360/licenses/LicenseHandlerTest.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/LicenseModerationRequestGenerator.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/TodoPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/licenses/LicensesPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/CompareTodos.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/add.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/detail.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailTodos.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/LicsExporter.java
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/utils/ConvertRecord.java
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/utils/TypeMappings.java
  libraries/exporters/src/test/java/org/eclipse/sw360/exporter/utils/ConvertRecordTest.java
  libraries/importers/src/main/java/org/eclipse/sw360/importer/LicsImporter.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftUtils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftValidate.java
  libraries/lib-datahandler/src/main/thrift/licenses.thrift
  libraries/lib-datahandler/src/main/thrift/moderation.thrift
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  scripts/migrations/023_rename_obligationType_to_obligationLevel.py
  scripts/migrations/024_update_type_from_obligations_to_obligation.py
  scripts/migrations/025_remove_old_obligations_view.py
  scripts/migrations/README.md
Labels: ready

#961 feat(ui): Sorted order of release in ReadmeOss, Clearing Report, Clearing Status Tree View.
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/OutputGenerator.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/LinkedReleasesAndProjectsAwarePortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
Labels: ready

#988 feat(LicenseInfoObligation): Rename Obligation in LicenseInfo.thrift to ObligationAtProject
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/AbstractCLIParser.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/CLIParser.java
  backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGeneratorTest.java
  backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/CLIParserTest.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsByReleases.jspf
  libraries/lib-datahandler/src/main/thrift/licenseinfo.thrift
Labels: needs code review, needs general test

#994 fix(UserSearch): Fixed search user functionality
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
Labels: ready

#997 feat(Project-UI): Added new field in Advanced Search for Projets
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectSearchHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
Labels: ready

#993 feat(ProjectUI): Added 2 new fields in Project Obligation
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/AbstractCLIParser.java
  backend/src/src-licenseinfo/src/main/resources/templateReport.docx
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligations.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsByReleases.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsEdit.jspf
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
  libraries/lib-datahandler/src/main/thrift/licenseinfo.thrift
  libraries/lib-datahandler/src/main/thrift/licenses.thrift
  libraries/lib-datahandler/src/main/thrift/projects.thrift
Labels: needs general test

#979 feat(rest): Adding pagination while listing projects and listing project releases
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGenerator.java
  libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGeneratorTest.java
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready
