Repository eclipse-sw360/sw360, pull requests merged in 2020-08, with the labels that each got.

#930 Fix import spdx information #927 #915 and change quotes
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/attachmentCleanup/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/databaseSanitation/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/licenseAdmin/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/vendors/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/clearingStatus.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/homepage/mytasksubmissions/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/includes/moderationHeader.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingRequest.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsEdit.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
Labels: ready

#926 chore(couchdb): Support CouchDb Lucene 2.1.0 with CouchDb 2.1.2 and backward compatibility
  build-configuration/resources/couchdb.properties
  build-configuration/test-resources/couchdb.properties
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/DatabaseSettings.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
Labels: needs code review, needs general test

#949 fix(Language_ja): change datatables.lang's URL
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
Labels: needs code review, needs general test

#916 yet another try: chore(java): migrating to openjdk java version 11
  .travis.yml
  README.md
  backend/src/src-fossology/pom.xml
  frontend/configuration/Private_Pages_7_3_3_GA4.lar
  frontend/configuration/Public_Pages_7_3_3_GA4.lar
  frontend/liferay-theme/pom.xml
  frontend/liferay-theme/src/main/webapp/WEB-INF/liferay-look-and-feel.xml
  frontend/liferay-theme/src/main/webapp/WEB-INF/liferay-plugin-package.properties
  frontend/sw360-portlet/bnd.bnd
  frontend/sw360-portlet/pom.xml
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/users/SSOAutoLogin.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/users/TestAutoLogin.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/sw360Wizard.js
  frontend/sw360-portlet/src/test/java/org/eclipse/sw360/portal/tags/links/DisplayDownloadAbstractTest.java
  libraries/commonIO/bnd.bnd
  libraries/exporters/bnd.bnd
  libraries/importers/bnd.bnd
  libraries/lib-datahandler/bnd.bnd
  libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/TestUtils.java
  pom.xml
  rest/authorization-server/pom.xml
  rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/Sw360AuthorizationServer.java
  rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/basicauth/Sw360LiferayAuthenticationProvider.java
  rest/resource-server/pom.xml
  scripts/install-thrift.sh
Labels: enhancement, needs code review, needs general test

#945 fix(ImportSPDXBOM): Set Default value[Default_Category] to categories field of Component if found null or empty
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
Labels: needs code review, needs general test

#929 feat(ui): Added link to project button from project detail view
  backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/searchProjects.jsp
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/lib-datahandler/src/main/thrift/projects.thrift
Labels: needs general test

#947 feat(ProjectReleaseRelation): Added new Field comment, createdOn, createdBy in ProjectReleaseRelation
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administrationEdit.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedProjectsRows.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleasesAjax.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleasesClearingStatusRows.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/linkedReleasesEdit.jspf
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/DatabaseMixInForChangeLog.java
  libraries/lib-datahandler/src/main/thrift/components.thrift
  libraries/lib-datahandler/src/main/thrift/sw360.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/serializer/JsonReleaseRelationSerializer.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready
