Repository eclipse-sw360/sw360, pull requests merged in 2020-12, with the labels that each got.

#1061 fix(ExportSpreadSheet): Fixed ClassNotFoundException while export Spreadsheet
  libraries/exporters/bnd.bnd
Labels: ready

#1056 feat(UtilityScript): Script for couchdb 2.x to update a field(String) in project document to a new value.
  scripts/utilities/001_update_project_field_value_couchdb_1_x.py
  scripts/utilities/003_update_project_field_value_couchdb_2_x.py
  scripts/utilities/README.md
Labels: ready

#1058 fix(rest): Fixed update Project API issue - unexpected changes in some fields like moderators ,contributors, etc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready

#1054 feat(ChangeLogs): Fixed issue related to null to empty string or collection conversion
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ChangeLogsDatabaseHandler.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/changelogs/elementView.jsp
Labels: needs general test

#1059 feat(ui-licenseobligation): License obligation changes
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/LicenseHandler.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/licenses/LicensesPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/add.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailAddTodo.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailTodos.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/licObligations.jsp
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
  libraries/lib-datahandler/src/main/thrift/licenses.thrift
  scripts/migrations/042_remove_validForProject_from_Obligation.py
Labels: needs general test

#1067 feat(SplitComponent): Add tooltip for releases of component with SourceCodeDownloadUrl and BinaryDownloadUrl during split feature
  backend/src-common/src/main/java/org/eclipse/sw360/components/summary/ReleaseSummary.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/splitComponent.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/mergeWizard.js
Labels: needs general test

#1070 feat(rest): Accept 'downloadurl' in request body as 'sourceCodeDownloadurl' as an alternative to original value 'sourceCodeDownloadurl' for Create and update Release APIs
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
Labels: ready

#1072 fix(clearingreport): Error while downloading clearing report
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxUtils.java
Labels: ready

#1062 feat(sw360Docker): Single container Docker for SW360
  Dockerfile
  README_DOCKER.md
  scripts/docker-config/etc_sw360/couchdb.properties
  scripts/docker-config/etc_sw360/sw360.properties
  scripts/docker-config/etc_sw360/welcomePageGuideline.html
  scripts/docker-config/install_scripts/build_couchdb_lucene.sh
  scripts/docker-config/install_scripts/download_liferay_and_dependencies.sh
  scripts/docker-config/install_scripts/entry_point.sh
  scripts/docker-config/install_scripts/install_configure_couchdb.sh
  scripts/docker-config/install_scripts/install_init_postgres_script.sh
  scripts/docker-config/mvn-proxy-settings.xml
  scripts/docker-config/portal-ext.properties
  scripts/docker-config/setenv.sh
Labels: needs code review, needs general test

#1077 feat(ui): Display Id in summary page of project, component and release
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/summary.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/summaryRelease.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/summary.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
Labels: needs code review, needs general test
