Repository eclipse-sw360/sw360, pull requests merged in 2020-02, with the labels that each got.

#774 fix(ui): saving attachment usage issue for source code bundle and others
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
Labels: ready

#748 Clean up some warning in the code
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/PropertyKeyMapping.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/serializer/JsonInstantSerializer.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/serializer/JsonProjectRelationSerializer.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/serializer/JsonReleaseRelationSerializer.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/licenseinfo/LicenseInfoController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/apiToken/ApiTokenAuthenticationProvider.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/keycloak/KeycloakAccessTokenConverter.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/configuration/security/Sw360AuthorizationServerConfiguration.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: needs general test

#755 feat(AddProjectReleaseRelation): add a project release relation for source code snippets
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/css/components/_tooltips.scss
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
  libraries/lib-datahandler/src/main/thrift/components.thrift
  libraries/lib-datahandler/src/main/thrift/sw360.thrift
  rest/resource-server/src/docs/asciidoc/components.adoc
Labels: needs rework

#653 Add spdx bom import functionality
  .travis/testForLicenseHeaders.sh
  backend/src-common/pom.xml
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/spdx/SpdxBOMImporter.java
  backend/src-common/src/main/java/org/eclipse/sw360/spdx/SpdxBOMImporterSink.java
  backend/src-common/src/test/java/org/eclipse/sw360/spdx/SpdxBOMImporterTest.java
  backend/src-common/src/test/resources/bom.spdx
  backend/src-common/src/test/resources/bom.spdx.rdf
  backend/src/src-attachments/src/main/java/org/eclipse/sw360/attachments/AttachmentHandler.java
  backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
  backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
  backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/attachmentsUpload.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/importBom.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/utils/includes/attachmentsUpload.js
  libraries/lib-datahandler/src/main/thrift/components.thrift
  libraries/lib-datahandler/src/main/thrift/projects.thrift
Labels: needs code review, needs general test

#752 fix(spreadsheet-export): fixed the sequence of values based on headers
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/helper/ReleaseHelper.java
Labels: ready

#770 feat(REST): Patch Releases to Project
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
  libraries/lib-datahandler/src/main/thrift/components.thrift
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready

#780 fix(EditReleaseUI): Fixed missing functionality of button to delete release to release relation.
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleasesRelationAjax.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/editLinkedReleases.jspf
Labels: needs code review, needs general test

#779 fix(REST): fixed search component by external id
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentRepository.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
  scripts/migrations/016_update_byExternalIds_component_view.py
  scripts/migrations/README.md
Labels: ready

#784 fix(ReleaseUI): fixed reload report in FOSSology Process
  backend/src/src-fossology/src/main/java/org/eclipse/sw360/fossology/FossologyHandler.java
Labels: ready

#776 feat(rest): validate the dependent document ids in the payload before updating it in the DB
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentAwareDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src/src-projects/src/test/java/org/eclipse/sw360/projects/ProjectHandlerTest.java
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  libraries/lib-datahandler/src/main/thrift/sw360.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
Labels: needs code review, needs general test

#786 fix(component/release): Add component/release error.
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
Labels: needs code review, needs general test

#794 chore(release): chaging files, readme, pom, changelog for 8.0.1
  CHANGELOG.md
  README.md
  pom.xml
Labels: needs code review, needs general test

#789 fix(REST): Updated upload attachment documentation
  rest/resource-server/src/docs/asciidoc/components.adoc
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/docs/asciidoc/releases.adoc
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/TestRestDocsSpecBase.java
Labels: needs code review, needs general test
