Repository eclipse-sw360/sw360, pull requests merged in 2020-10, with the labels that each got.

#978 feat(ui): Allow access to merge/split of component and release based on user role configured in properties
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/resources/sw360.properties
Labels: ready

#990 feat(LicenseDataModel): Merge LiceneObligation with Obligation
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/entitlement/LicenseModerator.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/LicenseHandler.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/ObligationRepository.java
  backend/src/src-licenses/src/test/java/org/eclipse/sw360/licenses/LicenseHandlerTest.java
  backend/src/src-licenses/src/test/java/org/eclipse/sw360/licenses/TestLicenseClient.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/ImportExportPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/licenses/LicensesPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/CompareTodos.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/detail.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailAddTodo.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailTodos.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/licenses/merge.jsp
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/LicsExporter.java
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/utils/ConvertRecord.java
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/utils/LicsArchive.java
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/utils/TypeMappings.java
  libraries/importers/src/main/java/org/eclipse/sw360/importer/LicsImporter.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftUtils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftValidate.java
  libraries/lib-datahandler/src/main/thrift/licenses.thrift
  scripts/migrations/026_licenseObligation_populate_text_field.py
  scripts/migrations/027_licenseObligation_field_update.py
  scripts/migrations/028_update_type_from_licenseObligation_to_obligation.py
  scripts/migrations/029_remove_old_licenseobligation_view.py
  scripts/migrations/030_obligation_field_update.py
  scripts/migrations/README.md
Labels: needs general test

#999 feat(obligation): Rename product obligation to project obligation
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/view.jsp
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
  libraries/lib-datahandler/src/main/thrift/licenses.thrift
  scripts/migrations/031_update_obligationLevel_from_productObligation_to_projectObligation.py
  scripts/migrations/README.md
Labels: ready

#1002 feat(ProjectObligation): Changes in Project Obligation Data Model
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ObligationListRepository.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
  backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/detail.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftUtils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftValidate.java
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  scripts/migrations/032_rename_linkedObligation_to_linkedObligationStatus_in_ProjectObligation.py
  scripts/migrations/033_update_type_from_projectObligation_to_obligationList.py
  scripts/migrations/034_remove_old_projectObligation_view.py
  scripts/migrations/README.md
Labels: needs general test

#1005 feat(licensemodel): Drop Risk and Risk category and merge it with Obligation
  backend/src-common/src/main/java/org/eclipse/sw360/components/summary/LicenseSummary.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/LicenseHandler.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/RiskCategoryRepository.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/RiskRepository.java
  backend/src/src-licenses/src/test/java/org/eclipse/sw360/licenses/LicenseHandlerTest.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailRisks.jspf
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/LicsExporter.java
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/utils/ConvertRecord.java
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/utils/LicsArchive.java
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/utils/TypeMappings.java
  libraries/importers/src/main/java/org/eclipse/sw360/importer/LicsImporter.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftUtils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftValidate.java
  libraries/lib-datahandler/src/main/thrift/licenses.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  scripts/migrations/035_risk_field_updates.py
  scripts/migrations/036_drop_old_views_and_license_field_update.py
  scripts/migrations/README.md
Labels: needs code review, needs general test

#1007 fix(moderation): Project moderation fix
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/Moderator.java
Labels: needs code review

#1009 fix(obligations):cover null pointer case if file with obligations is …
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
Labels: needs code review

#976 feat(CR-UI): Enhancement & Bug fixes
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/mail/MailConstants.java
  backend/src-common/src/main/java/org/eclipse/sw360/mail/MailUtil.java
  backend/src-common/src/main/resources/ClosedOrRejectedCREmailTemplate.html
  backend/src-common/src/main/resources/NewClearingRequestEmailTemplate.html
  backend/src-common/src/main/resources/UpdateClearingRequestEmailTemplate.html
  backend/src-common/src/main/resources/UpdateProjectWithCREmailTemplate.html
  backend/src-common/src/main/resources/sw360.properties
  backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
  frontend/liferay-theme/src/main/webapp/css/sw360/_sw360.scss
  frontend/liferay-theme/src/main/webapp/css/sw360/components/_progress.scss
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortletUtils.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/css/components/_tooltips.scss
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/clearing/clearingRequest.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/listgroup.js
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  libraries/lib-datahandler/src/main/thrift/sw360.thrift
Labels: needs code review, needs general test

#1017 fix(Obligation): Expand/Collapse all columns including comment using single leftmost toggle button for a row
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligations.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsEdit.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/utils/render.js
Labels: needs code review, needs general test

#1021 feat(ProjectTodo): Remove ProjectTodo and UI changes for Obligation and ProjectTodo
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src-common/src/test/java/org/eclipse/sw360/components/summary/ProjectSummaryTest.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/detail.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administration.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administrationEdit.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/linkedObligations.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligations.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsEdit.jspf
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/DatabaseMixInForChangeLog.java
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  scripts/migrations/037_checkfor_project_todos_in_moderations.py
  scripts/migrations/038_convert_ObligationStatusInfo_type_to_obligationType.py
  scripts/migrations/039_projecttodo_to_obligationlist.py
  scripts/migrations/README.md
Labels: needs code review, needs general test

#1025 feat(rest/ui): Project vulnerability endpoint update & added new project rating in UI
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
  libraries/lib-datahandler/src/main/thrift/vulnerabilities.thrift
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/Sw360VulnerabilityService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: needs code review, needs general test

#965 feat(ui-rest): Changes in Release information
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/entitytranslation/WsLibraryToSw360ReleaseTranslator.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/editReleaseInformation.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/summaryRelease.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeRelease.jsp
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ReleaseExporter.java
  libraries/importers/src/main/java/org/eclipse/sw360/importer/ComponentCSVRecord.java
  libraries/importers/src/main/java/org/eclipse/sw360/importer/ComponentCSVRecordBuilder.java
  libraries/importers/src/test/java/org/eclipse/sw360/importer/ComponentCSVRecordBuilderTest.java
  libraries/importers/src/test/resources/org/eclipse/sw360/importer/test-components.csv
  libraries/lib-datahandler/src/main/thrift/components.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
  scripts/migrations/040_rename_downloadurl_to_sourceCodeDownloadurl_in_Release.py
  scripts/migrations/041_update_release_moderation_with_downloadurl.py
  scripts/migrations/README.md
Labels: ready
