Repository eclipse-sw360/sw360, pull requests merged in 2020-01, with the labels that each got.

#737 fix(ReleaseUI/REST): prevent cyclic link in release
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentAwareDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/FossologyAwarePortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/editRelease.jsp
  libraries/lib-datahandler/src/main/thrift/components.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
Labels: needs code review, needs general test

#750 feat(Component/ReleaseUI): Added button to remove selected vendor for component and release
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayVendorEdit.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/css/main.scss
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/bulkReleaseEdit/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/editRelease.jsp
Labels: needs rework

#747 fix(ProjectUI): Show proper error msg ,when loading of project fails due to access or dependency not found.
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Assert.java
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  libraries/lib-datahandler/src/main/thrift/sw360.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
Labels: needs code review, needs general test

#749 chore(cleanup): drop unused and outdated code reated to the codescoop integration
  backend/src/pom.xml
  backend/src/src-codescoop/pom.xml
  backend/src/src-codescoop/src/main/java/org/eclipse/sw360/codescoop/CodescoopConfig.java
  backend/src/src-codescoop/src/main/java/org/eclipse/sw360/codescoop/CodescoopHandler.java
  backend/src/src-codescoop/src/main/java/org/eclipse/sw360/codescoop/CodescoopServlet.java
  backend/src/src-codescoop/src/main/java/org/eclipse/sw360/codescoop/CodescoopSpringServlet.java
  backend/src/src-codescoop/src/main/java/org/eclipse/sw360/codescoop/ModelTranslator.java
  backend/src/src-codescoop/src/main/resources/codescoop.properties
  backend/svc/pom.xml
  backend/svc/svc-codescoop/pom.xml
  backend/svc/svc-codescoop/src/main/webapp/WEB-INF/web.xml
  backend/svc/svc-codescoop/src/main/webapp/index.jsp
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/detail.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/editRelease.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/clearingStatus.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/editBasicInfo.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/editReleaseInformation.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/codeScoop.js
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftClients.java
  libraries/lib-datahandler/src/main/thrift/codescoop.thrift
Labels: needs code review, needs general test

#579 test: add script to start temporary couchdb with docker
  README.md
  scripts/startCouchdbForTests.sh
Labels: needs code review

#757 feat(updateViewScript): Script to update Views.
  scripts/migrations/015_update_fullmyprojects_view.py
  scripts/migrations/README.md
  scripts/utilities/002_update_view.py
  scripts/utilities/README.md
Labels: needs code review, needs general test

#758 Adding rolling versions based on commit count
  .travis.yml
  pom.xml
Labels: needs code review, needs general test

#763 fix(ui): fix issue #762, introduced in df5401472
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
Labels: needs general test

#761 Adding some more badges to the readme.
  README.md
Labels: question

#768 Updating files for release 7.0.1-M1
  CHANGELOG.md
  README.md
  pom.xml
Labels: needs code review, needs general test
