Repository eclipse-sw360/sw360, pull requests merged in 2021-05, with the labels that each got.

#1201 chore(rel): changing files for tagging 13.3
  CHANGELOG.md
  pom.xml
Labels: enhancement

#1188 feat(ProjectUI): feature to display the source files linked with the licenses
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/AbstractCLIParser.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/links/DisplayLicenseCollection.java
  frontend/sw360-portlet/src/main/resources/META-INF/customTags.tld
  frontend/sw360-portlet/src/main/resources/META-INF/resources/css/main.scss
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligations.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedProjectsRows.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleasesClearingStatusRows.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/dialog.js
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/utils/render.js
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
  libraries/lib-datahandler/src/main/thrift/components.thrift
  libraries/lib-datahandler/src/main/thrift/licenseinfo.thrift
Labels: ready

#1190 feat(rest): Added new endpoints to update attachment info of Project, Component, Release
  rest/resource-server/src/docs/asciidoc/components.adoc
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/docs/asciidoc/releases.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: ready

#1193 feat(rest): Added rest endpoint to update project-release-relationship information of linked releases in a project
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready

#1195 feat(ProjectGroupFilter):Filter the projects in Advanced Search based on Projects Group.
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
Labels: ready

#1198 feat(ProjectUI): Fixed copy of projects removes linked subprojects
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
Labels: needs code review

#1212 fix(backend): Issues with boolean and timestamp field deserialization and get attachment REST
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentOwnerRepository.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentRepository.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseRepositoryCloudantClient.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CustomThriftDeserializer.java
Labels: ready

#1216 feat(ProjectVersion): Added the project version in the Search option for the Projects filter.
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
Labels: needs code review, needs general test

#1214 fix(search): search releases while linking to project
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentSearchHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectSearchHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseSearchHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/UserSearchHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/VendorSearchHandler.java
  backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
  backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentSearchHandlerTest.java
  backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
  backend/src/src-search/src/main/java/org/eclipse/sw360/search/SearchHandler.java
  backend/src/src-search/src/main/java/org/eclipse/sw360/search/Sw360usersDatabaseSearchHandler.java
  backend/src/src-search/src/main/java/org/eclipse/sw360/search/db/AbstractDatabaseSearchHandler.java
  backend/src/src-search/src/main/java/org/eclipse/sw360/search/db/Sw360dbDatabaseSearchHandler.java
  backend/src/src-users/src/main/java/org/eclipse/sw360/users/db/UserDatabaseHandler.java
  backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorHandler.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
Labels: needs code review

#1220 fix(ui/rest): Issue fetching releases by external ids from REST and null value in external id breaks the release view
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayMapOfExternalIdsString.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseRepositoryCloudantClient.java
Labels: ready

#1227 feat(obligationlevelhelptext):Provide info text for different obligation Level.
  frontend/sw360-portlet/src/main/resources/META-INF/resources/css/components/_tooltips.scss
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/add.jsp
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
Labels: needs general test

#1231 fix(readmeossdownload): Null pointer while downloading readme_oss
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
Labels: ready

#1232 fix REST: Wrong error handling when deleting multiple components #851
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
Labels: ready

#1222 feat(moderations): Paginated view for requests tab for moderations
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ModerationSearchHandler.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/ModerationHandler.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/ModerationServlet.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationRequestRepository.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
  libraries/lib-datahandler/src/main/thrift/moderation.thrift
Labels: needs rework
