Repository eclipse-sw360/sw360, pull requests merged in 2021-03, with the labels that each got.

#1113 feat(ui):Rename and Re-arrange the Tabs under Projects section
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/clearingStatus.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
Labels: ready

#1117 feat(ProjectUI): Sort & Filter for ClearingStatus TreeView table
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jsp
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
Labels: ready

#1119 feat(ChangeLog): Highlight changes between old and new revision of Document
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/changelogs/elementView.jsp
Labels: ready

#1137 feat(MyProjectsUI):Add additional filter to My Projects homepage based on project clearing state.
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/MyProjectsPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/homepage/myprojects/view.jsp
Labels: ready

#1128 fix(script): Utility script to recompute clearing state of release
  scripts/utilities/004_recompute_clearing_state_of_release.py
  scripts/utilities/README.md
Labels: needs general test

#1147 bumping version to 13.1.0 in files, changelog
  CHANGELOG.md
  pom.xml
Labels: ready

#1157 fix(test): Use test databases in maven test phase
  backend/src-common/src/test/java/org/eclipse/sw360/datahandler/db/AttachmentDatabaseHandlerTest.java
  backend/src-common/src/test/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandlerTest.java
  backend/src/src-attachments/src/main/java/org/eclipse/sw360/attachments/AttachmentHandler.java
  backend/src/src-attachments/src/test/java/org/eclipse/sw360/attachments/AttachmentHandlerTest.java
  backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
  backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
  backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentSearchHandlerTest.java
  backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ProjectDatabaseHandlerTest.java
  backend/src/src-fossology/src/test/java/org/eclipse/sw360/fossology/FossologyHandlerLocalhostIntegrationTest.java
  backend/src/src-health/src/main/java/org/eclipse/sw360/health/HealthHandler.java
  backend/src/src-health/src/main/java/org/eclipse/sw360/health/db/HealthDatabaseHandler.java
  backend/src/src-health/src/test/java/org/eclipse/sw360/health/HealthHandlerTest.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/LicenseHandler.java
  backend/src/src-licenses/src/test/java/org/eclipse/sw360/licenses/LicenseHandlerTest.java
  backend/src/src-moderation/src/test/java/org/eclipse/sw360/moderation/testutil/DatabaseTestSetup.java
  backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
  backend/src/src-projects/src/test/java/org/eclipse/sw360/projects/ProjectHandlerTest.java
  backend/src/src-users/src/test/java/org/eclipse/sw360/users/UserHandlerTest.java
  backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorHandler.java
  backend/src/src-vendors/src/test/java/org/eclipse/sw360/vendors/TestVendorClient.java
  backend/src/src-vendors/src/test/java/org/eclipse/sw360/vendors/VendorHandlerTest.java
  backend/utils/src/test/java/org/eclipse/sw360/attachments/db/RemoteAttachmentDownloaderTest.java
  build-configuration/test-resources/couchdb-test.properties
  libraries/importers/src/test/java/org/eclipse/sw360/importer/ComponentAndAttachmentAwareDBTest.java
  libraries/lib-datahandler/src/main/thrift/health.thrift
  libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/TestUtils.java
  libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/common/DatabaseSettingsTest.java
Labels: needs code review, needs general test

#1138 fix(ReleaseUI): fix Spdx parser for License withh + sign
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTools.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/clearingDetails.jspf
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
Labels: ready
