Repository eclipse-sw360/sw360, pull requests merged in 2021-07, with the labels that each got.

#1270 feat(attachmentFilterForProject):skip unapproved attachments with filter.
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentSelectTable.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/licenseInfo.jsp
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
Labels: ready

#1280 fix(ui): Vulnerabilities relevance rating (tooltip) is not shown properly
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/CommonVulnerabilityPortletUtils.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/css/components/_tooltips.scss
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/vulnerabilities.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/vulnerabilities.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/vulnerabilities/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/bridges/datatables.js
Labels: ready

#1289 feat(ProjectUI): Added CLI count badge to release with CLI attachment
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentUsages.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentUsagesRows.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
Labels: needs code review, needs general test

#1265 feat(ui): Replace GPL compatibility by OSI approved/FSF libre in License
  backend/src-common/src/main/java/org/eclipse/sw360/components/summary/LicenseSummary.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/tools/SpdxConnector.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/licenses/LicensesPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayBoolean.java
  frontend/sw360-portlet/src/main/resources/META-INF/customTags.tld
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailSummary.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/editDetailSummary.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/utils/ConvertRecord.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
  libraries/lib-datahandler/src/main/thrift/licenses.thrift
  libraries/lib-datahandler/src/main/thrift/sw360.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
  scripts/migrations/044_replace_gpl_compatibility_by_osi_approved.py
Labels: ready

#1293 fix(ModerationRequest): Fixed Moderation Request for Project is not opening
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
Labels: needs general test

#1302 fix(ui): Fixed project list view, License Clearing column not loading
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
Labels: needs code review, needs general test

#1303 fix(script): Added DRY_RUN and updated readme
  scripts/migrations/044_replace_gpl_compatibility_by_osi_approved.py
  scripts/migrations/README.md
Labels: ready

#1297 feat(ui): sort the additional data of Project/Component/Release follow alphabet order
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeComponent.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeRelease.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/mergeWizard.js
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
Labels: ready

#1299 fix(RequestUi):BU & ProjectName not loading for Closed CR table
  backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/clearing/clearingRequest.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
Labels: ready

#1294 chore(ci): Migrating from travis ci to github actions
  .github/testForLicenseHeaders.sh
  .github/workflows/githubactions.yml
  .travis.yml
  scripts/install-thrift.sh
Labels: needs general test, needs rework

#1308 fix(UI): fix null pointer exception in additionalData sorting
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java
Labels: needs code review, needs general test

#1307 fix(ui): fix visibility of the group
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/ProjectPermissions.java
Labels: needs code review, needs general test

#1312 fix(ui): Fixed Generate License Info, Clearing Report and Source Code Download with/without subproject and showAll/onlyApproved filter
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentSelectTable.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/licenseInfo.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/sourceCodeBundle.jsp
  frontend/sw360-portlet/src/test/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtilsTest.java
Labels: needs general test

#1239 feat(ui): Add, Edit, Activate, Deactivate, Synchronize User from Admin - User Page
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/UserRepository.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/UserSearchHandler.java
  backend/src/src-users/src/main/java/org/eclipse/sw360/users/UserHandler.java
  backend/src/src-users/src/main/java/org/eclipse/sw360/users/db/UserDatabaseHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/LinkToPortletConfiguration.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/UserPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayMapOfSecondaryGroupAndRoles.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/users/HttpServletRequestAdapter.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/users/UserCSV.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/users/UserPortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/users/UserUtils.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/user/detail.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/user/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/user/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/clearing/clearingRequest.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingRequest.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/editSecondaryDepartmentAndRoles.jsp
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/lib-datahandler/src/main/thrift/users.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/apiToken/ApiTokenAuthenticationProvider.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/keycloak/KeycloakAccessTokenConverter.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java
Labels: needs general test

#1286 Adding contribution guidelines and code of conduct
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: needs code review, needs general test

#1315 fix(ClearingUI): ClearingExpert can't edit the CR
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/clearing/clearingRequest.jsp
Labels: ready

#1304 feat(ui/rest): Update project specific vulnerability action
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/CommonVulnerabilityPortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/css/components/_tooltips.scss
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/vulnerabilities.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/vulnerabilityModal.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/lib-datahandler/src/main/thrift/vulnerabilities.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: needs general test

#1319 fix(ui): Fixed js error in edit CR Page
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/clearing/clearingRequest.jsp
Labels: needs code review, needs general test

#1321 fix(ui): User should be able to edit group of project
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/basicInfo.jspf
Labels: needs code review, needs general test

#1295 feat(SVM): Added new field enableSvm(Default value - true) for linked project.
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src-common/src/test/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandlerTest.java
  backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ProjectDatabaseHandlerTest.java
  backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
  backend/src/src-projects/src/test/java/org/eclipse/sw360/projects/ProjectHandlerTest.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayProjectChanges.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/ajax/linkedProjectsAjax.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/linkedProjectsEdit.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/businessrules/ReleaseClearingStateSummaryComputer.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/DatabaseMixInForChangeLog.java
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/serializer/JsonProjectRelationSerializer.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
  scripts/migrations/045_migrate_project_linked_project_relation.py
  scripts/migrations/046_migrate_project_moderation_request_linked_project_relation.py
  scripts/migrations/README.md
Labels: ready

#1335 fix(ci) added new files to license check script
  .github/testForLicenseHeaders.sh
Labels: ready

#1326 fix(ui): Fixed create/update users with uppercase email or externalid
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/UserPortlet.java
Labels: ready
