Repository eclipse-sw360/sw360, pull requests merged in 2021-06, with the labels that each got.

#1233 fix(script): Build failure of compileWithDocker.sh #1230
  scripts/compileWithDocker.sh
  sw360dev.Dockerfile
Labels: ready

#1234 Fix: Rest interface can not handle licenses which do not exist in the database #534
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
Labels: ready

#1238 feat(ObligationHelpTextforProject): Provide the different obligation help text from the Projects Screen under Obligations tab.
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligations.jspf
Labels: ready

#1246 feat(rest): Support map of release id to usage as request body in addition to previous array of release id for - Link/Patch Releases to a Project API
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready

#1236 fix(rest): Auto-set release clearing state
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
Labels: ready

#1184 feat(VirusScanSchedulerService): Manual Scheduler service for deleting the attachment.
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
  backend/src-common/src/main/resources/sw360.properties
  backend/src/src-attachments/src/main/java/org/eclipse/sw360/attachments/AttachmentHandler.java
  backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
  backend/src/src-schedule/src/main/java/org/eclipse/sw360/schedule/service/ScheduleHandler.java
  backend/src/src-schedule/src/main/java/org/eclipse/sw360/schedule/timer/ScheduleConstants.java
  backend/src/src-schedule/src/main/resources/sw360.properties
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/ScheduleAdminPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/scheduleAdmin/view.jsp
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftClients.java
  libraries/lib-datahandler/src/main/thrift/attachments.thrift
Labels: ready

#1244 fix(ModerationRequests): moderation requests visibility
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/ModerationHandler.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationRequestRepository.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
  libraries/lib-datahandler/src/main/thrift/moderation.thrift
Labels: ready

#1253 fix(ModerationRequest): Accepting Moderation Request fails if it involves deletion of linked release or project from a project or release
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/Moderator.java
Labels: needs code review, needs general test

#1267 fix(ui): Link to main license detail page
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
Labels: ready

#1221 feat(mkdocs): sw360 Documentation.
  frontend/liferay-theme/src/main/webapp/templates/portal_normal.ftl
  frontend/sw360-portlet/pom.xml
  frontend/sw360-portlet/src/documentation/README.md
  frontend/sw360-portlet/src/documentation/index.html
  frontend/sw360-portlet/src/documentation/mkdocs.yml
  frontend/sw360-portlet/src/documentation/sw360docs/administrator-guide/admin-menu/ImagesBasic/admin_menu.png
  frontend/sw360-portlet/src/documentation/sw360docs/administrator-guide/admin-menu/admin-menu.md
  frontend/sw360-portlet/src/documentation/sw360docs/administrator-guide/properties/properties.md
  frontend/sw360-portlet/src/documentation/sw360docs/administrator-guide/user-management-roles/user-management-roles.md
  frontend/sw360-portlet/src/documentation/sw360docs/img/logo.png
  frontend/sw360-portlet/src/documentation/sw360docs/index.md
  frontend/sw360-portlet/src/documentation/sw360docs/stylesheets/extra.css
  frontend/sw360-portlet/src/documentation/sw360docs/sw360-RESTful-API/SW360RESTfulAPIImages/Preferences-AccessToke.png
  frontend/sw360-portlet/src/documentation/sw360docs/sw360-RESTful-API/SW360RESTfulAPIImages/Preferences-AccessToke1.png
  frontend/sw360-portlet/src/documentation/sw360docs/sw360-RESTful-API/SW360RESTfulAPIImages/techtokenreadexample.png
  frontend/sw360-portlet/src/documentation/sw360docs/sw360-RESTful-API/SW360RESTfulAPIImages/techtokenreadwriteexample.png
  frontend/sw360-portlet/src/documentation/sw360docs/sw360-RESTful-API/access.md
  frontend/sw360-portlet/src/documentation/sw360docs/sw360-RESTful-API/introduction.md
  frontend/sw360-portlet/src/documentation/sw360docs/sw360-best-practices/component-naming.md
  frontend/sw360-portlet/src/documentation/sw360docs/sw360-best-practices/dual_license.png
  frontend/sw360-portlet/src/documentation/sw360docs/sw360-best-practices/good-record-creation-structure.md
  frontend/sw360-portlet/src/documentation/sw360docs/sw360-best-practices/license-naming.md
  frontend/sw360-portlet/src/documentation/sw360docs/sw360-best-practices/sw360-best-practices.md
  frontend/sw360-portlet/src/documentation/sw360docs/sw360-user-FAQ/sw360-user-FAQ.md
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/component-and-releases/ImagesBasic/AddAttachment.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/component-and-releases/ImagesBasic/AddReleaseButton.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/component-and-releases/ImagesBasic/AddReleaseScreenWithoutData1.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/component-and-releases/ImagesBasic/AddReleaseScreenWithoutData2.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/component-and-releases/ImagesBasic/ComponentList.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/component-and-releases/ImagesBasic/ReleaseClearingDetails.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/component-and-releases/ImagesBasic/SearchVendor.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/component-and-releases/ImagesBasic/ViewComponent.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/component-and-releases/ImagesBasic/add_release.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/component-and-releases/ImagesBasic/clearing_detail.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/component-and-releases/ImagesBasic/comp_pg2.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/component-and-releases/ImagesBasic/comp_view.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/component-and-releases/ImagesBasic/create_comp.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/component-and-releases/ImagesBasic/create_release_new.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/component-and-releases/ImagesBasic/new_attachment.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/component-and-releases/ImagesBasic/new_comp.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/component-and-releases/ImagesBasic/new_comp_view.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/component-and-releases/ImagesBasic/release_list.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/component-and-releases/component-and-releases.md
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/login/ImagesBasic/SignIn.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/login/ImagesBasic/duo.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/login/ImagesBasic/homepage.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/login/ImagesBasic/start_page.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/login/login.md
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/projects/ImagesBasic/create_proj.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/projects/ImagesBasic/new_proj.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/projects/ImagesBasic/proj_pg2.png
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/projects/projects.md
  frontend/sw360-portlet/src/documentation/sw360docs/user-guide/tasks-for-experts/tasks-for-experts.md
  rest/resource-server/pom.xml
Labels: needs code review, needs general test

#1250 feat(ClearingRequestUI): Bug fixes and enhancement
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/ModerationHandler.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ClearingRequestRepository.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/CustomFieldHelper.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/css/components/_tooltips.scss
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/clearing/clearingRequest.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingRequest.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/dialog.js
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/validation.js
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/utils/render.js
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
  libraries/lib-datahandler/src/main/thrift/moderation.thrift
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  libraries/lib-datahandler/src/main/thrift/sw360.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ClearingRequestSpecTest.java
Labels: ready

#1279 fix(rest): Issue updating newly created release via REST and issue with get project by id
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseConnectorCloudant.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
Labels: ready

#1266 feat(rest): Add Rest APIs related to obligation
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftValidate.java
  rest/resource-server/src/docs/asciidoc/api-guide.adoc
  rest/resource-server/src/docs/asciidoc/licenses.adoc
  rest/resource-server/src/docs/asciidoc/obligations.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/HalResource.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/obligation/ObligationController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/obligation/ObligationResourceProcessor.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/obligation/Sw360ObligationService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ApiSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ObligationSpecTest.java
Labels: ready

#1257 feat(rest): Added rest apis for create, update, delete vulnerability and create, delete vulnerability release relation
  backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/VulnerabilityHandler.java
  backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/db/VulnerabilityDatabaseHandler.java
  libraries/lib-datahandler/src/main/thrift/vulnerabilities.thrift
  rest/resource-server/src/docs/asciidoc/vulnerabilities.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/ResourceServerConfiguration.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/Sw360VulnerabilityService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VulnerabilitySpecTest.java
Labels: ready

#1256 feat(ui): Added support to add external URLs to project
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src-common/src/test/java/org/eclipse/sw360/components/summary/ProjectSummaryTest.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayMapOfExternalUrls.java
  frontend/sw360-portlet/src/main/resources/META-INF/customTags.tld
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/basicInfo.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/summary.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/editExternalUrls.jsp
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
  scripts/migrations/043_migrate_project_homepage_wiki_to_externalUrls.py
  scripts/migrations/README.md
Labels: ready

#1283 feat(ProjectUI): Improvements in AddLicenseInfoToRelease & Obligation tab UI
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligations.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsEdit.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  frontend/sw360-portlet/src/main/resources/sw360.properties
Labels: needs code review, needs general test

#1272 fix(ModerationRequests): Updated views with queries
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationRequestRepository.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseConnectorCloudant.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseRepositoryCloudantClient.java
Labels: needs special test
