Repository eclipse-sw360/sw360, pull requests merged in 2021-08, with the labels that each got.

#1318 feat(ReleaseUI): License to SourceFile Mapping
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/FossologyAwarePortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/links/DisplayLicenseCollection.java
  frontend/sw360-portlet/src/main/resources/META-INF/customTags.tld
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/summaryRelease.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleasesClearingStatusRows.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/licenseToSrcMapping.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
Labels: needs code review, needs general test

#1310 feat(rest): Add Rest API for linking release to release
  rest/resource-server/src/docs/asciidoc/releases.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: ready

#1328 fix(Rest):make SW360 REST API Get Releases by Name Case-Insensitive.
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
Labels: ready

#1330 fix(MyProjectErrorMessageUI):update the error message in UI for the project which is not accessible.
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
Labels: enhancement, ready

#1309 fix(script): Update CouchDB version and add password and user
  scripts/startCouchdbForTests.sh
Labels: ready

#1334 fix(DBTestsFail): Migrating databasetest.properties to couchdb-test.properties.
  .github/workflows/githubactions.yml
  libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/couchdb/DatabaseTestProperties.java
  libraries/lib-datahandler/src/test/resources/databasetest.properties
Labels: needs general test

#1341 feat(log): Added output processing of the change log
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
  backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
  build-configuration/resources/log4j2.xml
Labels: needs code review, needs general test

#1344 fix(ui): Changes in External urls in Project are not registered in Moderation Request. Closed Moderation Request doesnot show Proposed changes
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ProjectModerationRequestGenerator.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/CompareAttachments.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/CompareTodos.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayComponentChanges.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayProjectChanges.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayReleaseChanges.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/TagUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/urlutils/LinkedReleaseRenderer.java
  frontend/sw360-portlet/src/main/resources/META-INF/customTags.tld
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/components/merge.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/licenses/merge.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/projects/merge.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/releases/merge.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/users/merge.jsp
Labels: ready

#1348 fix(ui): Fixed js error while merge component/release with null additional data
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeComponent.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeRelease.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/mergeWizard.js
Labels: ready

#1350 fix(ui): Cleanup moderation request on deleting project/release/component
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationRequestRepository.java
Labels: needs code review, needs general test

#1342 fix(rest): Added exception processing for authorization
  rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/basicauth/Sw360LiferayAuthenticationProvider.java
Labels: ready

#1323 fix(docker):Update couchdb3.1 ubuntu20.04 liferay7.3.4 postgresql12
  Dockerfile
  scripts/docker-config/etc_sw360/authorization/application.yml
  scripts/docker-config/etc_sw360/couchdb.properties
  scripts/docker-config/install_scripts/build_couchdb_lucene.sh
  scripts/docker-config/install_scripts/download_liferay_and_dependencies.sh
  scripts/docker-config/install_scripts/entry_point.sh
  scripts/docker-config/install_scripts/install_configure_couchdb.sh
  scripts/docker-config/install_scripts/install_init_postgres_script.sh
Labels: needs code review, needs general test

#1359 fix(RestAPI):500 Internal server error from releases API.
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
Labels: ready

#1285 fix(upgradeVersion):Upgrade version.
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
  backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
  frontend/sw360-portlet/pom.xml
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ThriftJsonSerializer.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/AttachmentAwarePortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/VendorPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseConnectorCloudant.java
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  pom.xml
  rest/authorization-server/pom.xml
  rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/Sw360AuthorizationServer.java
  rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/client/persistence/OAuthClientRepository.java
  rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/Sw360WebSecurityConfiguration.java
  rest/authorization-server/src/test/java/org/eclipse/sw360/rest/authserver/IntegrationTestBase.java
  rest/resource-server/pom.xml
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/ResourceServerConfiguration.java
  rest/resource-server/src/main/resources/application.yml
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/SW360RestHealthIndicatorTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentServiceTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/configuration/security/Sw360WebSecurityConfiguration.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ApiSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/AttachmentSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ChangeLogSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ClearingRequestSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/HealthSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ObligationSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/SearchSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VendorSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VulnerabilitySpecTest.java
  rest/resource-server/src/test/resources/application.properties
  rest/rest-common/src/main/java/org/eclipse/sw360/rest/common/Sw360CORSFilter.java
  scripts/install-thrift.sh
Labels: needs general test
