Repository eclipse-sw360/sw360, pull requests merged in 2022-09, with the labels that each got.

#1627 fix(ui): Generate portlet X url inside portlet Y
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ChangeLogsPortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
Labels: ready

#1631 fix(ProjectUI): fixed Release filter bug in AttachmentUsage tab
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentUsagesRows.jspf
Labels: needs code review, needs general test

#1626 fix(report): Nullpointer downloading report
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
Labels: needs code review, needs general test

#1569 fix(CrUi): fix the critical CR creation issue
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/ModerationHandler.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ClearingRequestRepository.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
  libraries/lib-datahandler/src/main/thrift/moderation.thrift
Labels: ready

#1598 fix(UI): Disable write access from UI
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/preferences/view.jsp
  frontend/sw360-portlet/src/main/resources/sw360.properties
Labels: ready

#1635 upd(maven): Update maven build infra
  .dockerignore
  .github/workflows/githubactions.yml
  Dockerfile
  README.md
  backend/pom.xml
  clients/client/src/test/java/org/eclipse/sw360/clients/rest/AbstractMockServerTest.java
  clients/client/src/test/resources/rest-test.properties
  frontend/configuration/setenv.sh
  frontend/liferay-theme/pom.xml
  frontend/liferay-theme/src/main/webapp/WEB-INF/web.xml
  libraries/lib-datahandler/pom.xml
  libraries/log4j-osgi-support/pom.xml
  pom.xml
  scripts/docker-config/setenv.sh
  scripts/startCouchdbForTests.sh
  scripts/sw360BackendRestDockerConfig/etc_sw360/rest-test.properties
  scripts/sw360BackendRestDockerConfig/scripts/createUserAndOauthClient.sh
Labels: needs code review, technical debt, ready

#1638 chores(liferay): updated liferay kernel and theme
  backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/datasource/json/CveSearchJsonParserTest.java
  backend/src/src-licenses/pom.xml
  frontend/liferay-theme/pom.xml
  frontend/liferay-theme/src/main/webapp/css/_custom.scss
  frontend/liferay-theme/src/main/webapp/css/portal/_alert.scss
  frontend/liferay-theme/src/main/webapp/css/portlet/_portlet_decorators.scss
  frontend/liferay-theme/src/main/webapp/templates/portal_normal.ftl
  frontend/sw360-portlet/bnd.bnd
  frontend/sw360-portlet/pom.xml
Labels: needs code review, needs general test

#1632 fix(ui): Fixed lar file to add missing widgets(Oauth Client & License Types)
  frontend/configuration/Private_Pages_7_4_3_18_GA18.lar
Labels: ready

#1580 fix/svmcomponentids - do not copy svm component ids
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/resources/sw360.properties
Labels: ready

#1608 fix(rest): Added component type tag in release api
  libraries/lib-datahandler/src/main/thrift/components.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: ready

#1636 fix(ecc): Script to cleanup ECC information in release
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/eccDetails.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/editReleaseECCInformation.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeRelease.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/eccStatus.jspf
  libraries/importers/src/main/java/org/eclipse/sw360/importer/ComponentCSVRecord.java
  libraries/importers/src/main/java/org/eclipse/sw360/importer/ComponentCSVRecordBuilder.java
  libraries/importers/src/test/java/org/eclipse/sw360/importer/ComponentCSVRecordBuilderTest.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/DatabaseMixInForChangeLog.java
  libraries/lib-datahandler/src/main/thrift/components.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  scripts/migrations/050_cleanup_eccinformation_duplicate_attributes.py
  scripts/migrations/README.md
Labels: ready

#1640 fix(ecc): Script to change ECC status in Release
  scripts/migrations/051_change_eccStatus.py
  scripts/migrations/README.md
Labels: ready
