Repository eclipse-sw360/sw360, pull requests merged in 2022-11, with the labels that each got.

#1696 upd(docker): Push sw360 docker image to Github Registry
  .github/workflows/build_and_test.yml
  .github/workflows/docker_deploy.yml
  Dockerfile
  README_DOCKER.md
  docker-compose.yml
  docker_build.sh
  scripts/download_dependencies.sh
Labels: enhancement

#1711 Revert mistake on library installs
  .dockerignore
  Dockerfile
  frontend/sw360-portlet/pom.xml
  libraries/commonIO/pom.xml
  libraries/datahandler/pom.xml
  libraries/exporters/pom.xml
  libraries/importers/pom.xml
  libraries/log4j-osgi-support/pom.xml
  scripts/install-thrift.sh
  scripts/versions.sh
Labels: ready

#1708 fix(User): CountryId does not exists while creating user with new Organization
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/UserPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/users/OrganizationHelper.java
  frontend/sw360-portlet/src/main/resources/sw360.properties
Labels: ready

#1670 Added access for deleting merge source release for clearing admin
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/DocumentPermissions.java
  libraries/datahandler/src/test/java/org/eclipse/sw360/datahandler/permissions/ProjectPermissionsTest.java
Labels: ready

#1605 fix(CouchDbView): Improve couchdb view performance
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentUsageRepository.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ChangeLogsRepository.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ConfigContainerRepository.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/CustomPropertiesRepository.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ObligationListRepository.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectVulnerabilityRatingRepository.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/RelationsUsageRepository.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseRepository.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseTypeRepository.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/ObligationElementRepository.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/ObligationNodeRepository.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ClearingRequestRepository.java
  backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/db/VulnerabilityRelationRepository.java
  rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/client/persistence/OAuthClientRepository.java
Labels: ready

#1634 feat(ui): Banner to Broadcast Messages
  frontend/liferay-theme/src/main/webapp/css/portal/_header.scss
  frontend/liferay-theme/src/main/webapp/js/banner.js
  frontend/liferay-theme/src/main/webapp/templates/portal_normal.ftl
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/CustomFieldHelper.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/MySubscriptionsPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/attachmentCleanup/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/bulkReleaseEdit/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/databaseSanitation/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/fossyAdmin/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/importexport/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/licenseAdmin/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/licenseTypes/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/oauthclient/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/scheduleAdmin/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/user/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/user/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/vendors/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/vendors/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/changelogs/elementView.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/editRelease.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/ecc/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/homepage/myprojects/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/detail.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/clearing/clearingRequest.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/preferences/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/search/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/vulnerabilities/detail.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/vulnerabilities/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/bannerMessage.js
Labels: ready

#1710 fix(UI): Text field is blank while ExportSpread in licenses
  backend/src-common/src/main/java/org/eclipse/sw360/components/summary/LicenseSummary.java
Labels: ready

#1698 fix(UI): Added code to show the project list in component tab
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
Labels: ready

#1667 Update the REST-API documentation for Definition of Manufacturer on project level
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready

#1723 fix(PreferencesUI):Read Access has to be checked before Generating token
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/preferences/view.jsp
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
Labels: ready

#1728 fix(ProjectUI): Multiple alerts when there are same linked projects
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
Labels: ready

#1730 upd(README): Update with new information
  README.md
Labels: enhancement

#1694 fix(UI): Unresponsive UI & top align session message
  frontend/liferay-theme/src/main/webapp/css/portal/_alert.scss
  frontend/liferay-theme/src/main/webapp/templates/portal_normal.ftl
Labels: ready

#1733 feat(SPDX): Upgrade tools-java library to support SPDX 2.3 format
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/importBom.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/importBomForComponent.jspf
  pom.xml
Labels: needs general test

#1725 feat(AdminUI): Changed the title of the button to 'Update' from 'Edit' in Edit Client modal in OauthClient and set the validity to 'Days' by default
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/oauthclient/view.jsp
Labels: ready

#1739 feat(ProjectUI):License Info In the Spreadsheet Exported from Project License Clearing
  libraries/datahandler/src/main/thrift/components.thrift
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ReleaseExporter.java
Labels: ready

#1703 feat(RESTapi): created new endpoint for clearingrequest and modified existing endpoint payload
  rest/resource-server/src/docs/asciidoc/api-guide.adoc
  rest/resource-server/src/docs/asciidoc/clearingRequests.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/AttachmentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/ClearingRequestController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/ClearingRequestResourceProcessor.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/Sw360ClearingRequestService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ApiSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ClearingRequestSpecTest.java
Labels: ready

#1727 Feat(UI): apply sorting in release versions when inspecting component
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
Labels: ready
