Repository eclipse-sw360/sw360, pull requests merged in 2022-02, with the labels that each got.

#1457 chore(rel): changing files for tagging 15.0
  CHANGELOG.md
  pom.xml
Labels: ready

#1460 chore(rel): Changing back to 15.1.0-SNAPSHOT
  pom.xml
Labels: ready

#1357 fix(ui): Restrict visibility of each component/release like Project
  .github/workflows/githubactions.yml
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentSearchHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/spdx/SpdxBOMImporterSink.java
  backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
  backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ProjectDatabaseHandlerTest.java
  backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
  backend/src/src-search/src/main/java/org/eclipse/sw360/search/db/Sw360dbDatabaseSearchHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/FossologyAwarePortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/LinkedReleasesAndProjectsAwarePortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/VendorPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/ecc/EccPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/RecentReleasesPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/detail.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/editBasicInfo.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/summary.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/homepage/recentcomponents/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/homepage/recentreleases/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentSelectTable.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentUsagesRows.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/eccStatus.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedProjectsRows.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleasesAjax.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleasesClearingStatusRows.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleasesRelationAjax.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleasesRows.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/editLinkedReleases.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/usingComponentsTable.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  frontend/sw360-portlet/src/main/resources/sw360.properties
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/helper/ProjectHelper.java
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/helper/ReleaseHelper.java
  libraries/importers/src/main/java/org/eclipse/sw360/importer/ComponentImportUtils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/ComponentPermissions.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/PermissionUtils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/ReleasePermissions.java
  libraries/lib-datahandler/src/main/resources/sw360.properties
  libraries/lib-datahandler/src/main/thrift/components.thrift
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/permissions/ComponentPermissionsVisibilityTest.java
  libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/permissions/jgivens/GivenComponent.java
  libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/permissions/jgivens/WhenComputeComponentVisibility.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
  scripts/migrations/048_add_component_businessunit.py
Labels: increases minor version, ready

#1440 fix(ui): Search function does not work if Keyword is empty
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/search/SearchPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/search/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/images/icons.svg
Labels: ready

#1447 feat(project): Added vendor for project
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/VendorRepository.java
  backend/src-common/src/test/java/org/eclipse/sw360/components/summary/ProjectSummaryTest.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/basicInfo.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/vendors/vendorDetail.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectExporter.java
  libraries/lib-datahandler/src/main/thrift/projects.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Labels: ready

#1452 fix(ui): Fixed pagination of component list with search params
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
Labels: ready

#1456 feat(script): Addition to update project field starting with some value
  scripts/utilities/003_update_project_field_value_couchdb_2_x.py
  scripts/utilities/README.md
Labels: ready

#1432 New docker overhaul using Docker Compose
  .gitignore
  Dockerfile
  README_DOCKER.md
  docker-compose.yml
  docker_build.sh
  fossology-docker-compose.yml
  scripts/docker-config/couchdb-lucene.ini
  scripts/docker-config/default.docker.env
  scripts/docker-config/download_dependencies.sh
  scripts/docker-config/entry_point.sh
  scripts/docker-config/etc_sw360/authorization/application.yml
  scripts/docker-config/etc_sw360/couchdb.properties
  scripts/docker-config/etc_sw360/rest/application.yml
  scripts/docker-config/install_scripts/build_couchdb_lucene.sh
  scripts/docker-config/install_scripts/build_thrift.sh
  scripts/docker-config/install_scripts/configure_couchdb.sh
  scripts/docker-config/install_scripts/download_liferay_and_dependencies.sh
  scripts/docker-config/install_scripts/entry_point.sh
  scripts/docker-config/install_scripts/install_configure_couchdb.sh
  scripts/docker-config/install_scripts/install_init_postgres_script.sh
  scripts/docker-config/mvn-proxy-settings.xml
  scripts/docker-config/pg-init-scripts/fossology.sql
  scripts/docker-config/portal-ext.properties
  scripts/docker-config/set_proxy.sh
Labels: needs code review, needs general test

#1453 fix(api): Correct the ECC status when release is created by API
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
  backend/src-common/src/main/resources/sw360.properties
Labels: ready

#1462 feat(projectUi): Update some fields in a Project in closed state
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
Labels: ready
