Repository eclipse-sw360/sw360, pull requests merged in 2022-07, with the labels that each got.

#1567 fix(rest): Added release main licenses in the response
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
Labels: ready

#1578 feat(ReleaseUi):Display AssessmentSummary info from CLI xml in Release details page
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/CLIParser.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/css/components/_table.scss
  frontend/sw360-portlet/src/main/resources/META-INF/resources/css/main.scss
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/clearingDetails.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/lib-datahandler/src/main/thrift/licenseinfo.thrift
Labels: needs code review

#1549 fix(project): Added write permissions for closed project
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/ProjectPermissions.java
  libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/permissions/ProjectPermissionsTest.java
Labels: ready

#1590 feat(ui):filter active users
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/UserRepository.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/UserPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/user/view.jsp
Labels: ready

#1591 Fix (Component): Fix bug component list sorting
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
Labels: ready

#1599 upd(mockito): Update the deprecated old mockito-all to mockito-core
  backend/pom.xml
  backend/src-common/src/test/java/org/eclipse/sw360/datahandler/db/AttachmentAwareDatabaseHandlerTest.java
  backend/src-common/src/test/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandlerTest.java
  backend/src-common/src/test/java/org/eclipse/sw360/spdx/SpdxBOMImporterTest.java
  backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
  backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ProjectDatabaseHandlerTest.java
  backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/datasink/VulnerabilityConnectorTest.java
  backend/src/src-fossology/src/test/java/org/eclipse/sw360/fossology/FossologyHandlerLocalhostIntegrationTest.java
  backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandlerTest.java
  backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/TestHelper.java
  backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/CLIParserTest.java
  backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/CombinedCLIParserTest.java
  clients/client/src/test/java/org/eclipse/sw360/clients/adapter/SW360ComponentClientAdapterAsyncImplTest.java
  clients/client/src/test/java/org/eclipse/sw360/clients/adapter/SW360LicenseClientAdapterAsyncImplTest.java
  clients/client/src/test/java/org/eclipse/sw360/clients/adapter/SW360ProjectClientAdapterAsyncImplTest.java
  clients/client/src/test/java/org/eclipse/sw360/clients/adapter/SW360ReleaseClientAdapterAsyncImplTest.java
  clients/client/src/test/java/org/eclipse/sw360/clients/adapter/SW360VulnerabilityClientAdapterAsyncImplTest.java
  clients/http-support/src/test/java/org/eclipse/sw360/http/utils/HttpUtilsTest.java
  frontend/sw360-portlet/pom.xml
  frontend/sw360-portlet/src/test/java/org/eclipse/sw360/portal/portlets/projectimport/BdpImportPortletTest.java
  frontend/sw360-portlet/src/test/java/org/eclipse/sw360/portal/portlets/projectimport/WsImportPortletTest.java
  frontend/sw360-portlet/src/test/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletTest.java
  frontend/sw360-portlet/src/test/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtilsTest.java
  frontend/sw360-portlet/src/test/java/org/eclipse/sw360/portal/tags/links/DisplayDownloadAbstractTest.java
  libraries/exporters/pom.xml
  libraries/exporters/src/test/java/org/eclipse/sw360/exporter/ProjectExporterTest.java
  libraries/importers/pom.xml
  libraries/importers/src/test/java/org/eclipse/sw360/importer/ComponentAndAttachmentAwareDBTest.java
  libraries/lib-datahandler/bnd.bnd
  libraries/lib-datahandler/pom.xml
  libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/couchdb/AttachmentConnectorTest.java
  libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/couchdb/AttachmentContentDownloaderTest.java
  libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/couchdb/AttachmentStreamConnectorTest.java
  libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/couchdb/DatabaseTestProperties.java
  libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/permissions/ReleasePermissionsTest.java
  libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/resourcelists/PaginationOptionsTest.java
  libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/resourcelists/PaginationResultTest.java
  libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGeneratorTest.java
  libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/resourcelists/ResourceListControllerTest.java
  pom.xml
  rest/pom.xml
  scripts/install-thrift.sh
Labels: enhancement, ready, dependencies
