Repository eclipse-sw360/sw360, pull requests merged in 2022-10, with the labels that each got.

#1594 feat(SPDX): Use new SPDX library (#1496)
  backend/src-common/pom.xml
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/spdx/SpdxBOMImporter.java
  backend/src-common/src/test/java/org/eclipse/sw360/spdx/SpdxBOMImporterTest.java
  backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
  backend/src/src-fossology/src/main/java/org/eclipse/sw360/fossology/rest/FossologyRestClient.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/changelogs/elementView.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/clearingDetails.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/importBom.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/importBomForComponent.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/usingProjectsTable.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
  libraries/lib-datahandler/src/main/thrift/attachments.thrift
  libraries/lib-datahandler/src/main/thrift/components.thrift
  libraries/lib-datahandler/src/main/thrift/sw360.thrift
  pom.xml
Labels: ready

#1662 fix(SBOM): Fixed Component type is not being set when components are …
  backend/src-common/src/main/java/org/eclipse/sw360/spdx/SpdxBOMImporter.java
Labels: needs code review, needs general test

#1679 Fix(Docs): rest and mk docs
  pom.xml
  rest/resource-server/pom.xml
Labels: needs code review, needs general test

#1673 fix(ComponentUI):HTML encoded character in Vendor field
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
Labels: ready

#1655 fix(ecc): Reset Ecc Fields when Component type is changed.
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
Labels: ready

#1680 feat(buildsystem): Rearrange dependencies and deployments
  .github/testForLicenseHeaders.sh
  .github/workflows/githubactions.yml
  Dockerfile
  frontend/sw360-portlet/pom.xml
  libraries/commonIO/pom.xml
  libraries/datahandler/pom.xml
  libraries/exporters/pom.xml
  libraries/importers/pom.xml
  libraries/log4j-osgi-support/pom.xml
  pom.xml
  utils/pom.xml
Labels: needs code review, needs general test, breaking change
