Repository eclipse-sw360/sw360, pull requests merged in 2022-08, with the labels that each got.

#1602 chore(dependencies): spring vulnerability - cve-2022-22970,cve-2022-22971
  pom.xml
Labels: ready

#1537 fix(REST): fixed release update issue for releases with invalid licenses
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ReleaseTest.java
Labels: ready

#1552 feat(search): allow searching for external ids
  backend/src/src-search/src/main/java/org/eclipse/sw360/search/SearchHandler.java
  backend/src/src-search/src/main/java/org/eclipse/sw360/search/db/AbstractDatabaseSearchHandler.java
  libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
Labels: ready

#1563 fix(AdminUI): Prevent license type duplication with case insensitive check
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseTypeRepository.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailText.jspf
Labels: ready

#1575 feat(ui) : select your group in Project page by grid
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayDepartmentEdit.java
  frontend/sw360-portlet/src/main/resources/META-INF/customTags.tld
  frontend/sw360-portlet/src/main/resources/META-INF/resources/css/components/_form.scss
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/ajax/departmentSearch.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/editBasicInfo.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/departments/searchDepartment.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/basicInfo.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/components/includes/departments/searchDepartment.js
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
Labels: ready

#1603 feat(ui): Add banner to broadcast messages
  frontend/liferay-theme/src/main/webapp/css/portal/_header.scss
  frontend/liferay-theme/src/main/webapp/js/banner.js
  frontend/liferay-theme/src/main/webapp/templates/portal_normal.ftl
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/CustomFieldHelper.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/MySubscriptionsPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/init.jsp
Labels: ready

#1508 chores(upgrade): Upgrade Liferay to 7.4.3.18 GA18
  frontend/configuration/Private_Pages_7_4_3_18_GA18.lar
  frontend/configuration/Public_Pages_7_4_3_18_GA18.lar
  frontend/configuration/portal-ext.properties
  frontend/liferay-theme/src/main/webapp/WEB-INF/liferay-look-and-feel.xml
  frontend/liferay-theme/src/main/webapp/WEB-INF/liferay-plugin-package.properties
  frontend/liferay-theme/src/main/webapp/css/_custom.scss
  frontend/liferay-theme/src/main/webapp/css/portal/_alert.scss
  frontend/liferay-theme/src/main/webapp/css/portlet/_portlet_decorators.scss
  frontend/liferay-theme/src/main/webapp/templates/portal_normal.ftl
  frontend/sw360-portlet/bnd.bnd
  frontend/sw360-portlet/pom.xml
  scripts/docker-config/portal-ext.properties
Labels: needs code review, needs general test, priority

#1596 Hcc/liferay upgrade extension
  .gitignore
  Dockerfile
  docker-compose.yml
  docker_build.sh
  frontend/configuration/portal-ext.properties
  libraries/lib-datahandler/pom.xml
  pom.xml
  rest/authorization-server/pom.xml
  rest/resource-server/pom.xml
  rest/rest-common/pom.xml
  scripts/docker-config/portal-ext.properties
  scripts/download_dependencies.sh
Labels: enhancement, has merge conflicts, needs special test, ready

#1592 feat(UI):Made the table header collapsible wherever possible
  frontend/sw360-portlet/src/main/resources/META-INF/resources/css/main.scss
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/summary.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/clearingDetails.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/commercialDetails.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/eccDetails.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/summaryRelease.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/vendors/vendorDetail.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administration.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/summary.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/vendors/vendorDetail.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
Labels: ready

#1573 feat(ProjectUI): Load License info header text based on project group
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  libraries/lib-datahandler/src/main/thrift/licenseinfo.thrift
Labels: ready

#1582 fix(ui): cannot link Component with closed project
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/components/includes/releases/linkProject.js
Labels: needs code review
