Repository eclipse-sw360/sw360, pull requests merged in 2023-07, with the labels that each got.

#1970 feat(rest): new endpoint merge components
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  rest/resource-server/src/docs/asciidoc/components.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
Labels: REST, ready, New-UI

#2019 fix(UI): Sorting release versions in drop down menu
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
Labels: ready

#2024 fix(Rest): Add clearing information in release response (New Front-end)
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: needs code review, needs general test, REST, New-UI

#2027 fix(rest): fix test rest api of component
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
Labels: ready

#2022 fix(Rest): Allowing search for externalIds without encoding
  clients/client/src/main/java/org/eclipse/sw360/clients/rest/SW360ReleaseClient.java
  clients/client/src/test/java/org/eclipse/sw360/clients/rest/SW360ReleaseClientIT.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: needs code review, needs general test

#1965 feat(rest) - Rest API for downloading components report.
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
  libraries/datahandler/src/main/thrift/components.thrift
  rest/resource-server/src/docs/asciidoc/components.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: REST, ready, New-UI

#2020 feat(ProjectObligationsEdit): Save comment and status fields on edit
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsEdit.jspf
Labels: enhancement, ready

#2033 fix(UI):word correction of Initial use scan in attachment type
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
Labels: needs code review

#2028 feat(rest): To list linked projects of sub-projects.
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: REST, ready, New-UI

#2046 feat(rest):Adding new fields to get list of project vulnerability
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready

#2045 feat(ExportSpreadsheet): Add project and release ID to the exported excel
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectExporter.java
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ReleaseExporter.java
Labels: enhancement

#2043 fix(Rest): Allowing search for components without encoding
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
Labels: ready

#2007 feat(REST): New endpoint split components.
  rest/resource-server/src/docs/asciidoc/components.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
Labels: REST, ready, New-UI

#2058 fix(doc): remove merge conflict notation
  rest/resource-server/src/docs/asciidoc/components.adoc
Labels: ready

#2047 New endpoint allow to re-generate fossology report (New Frontend)
  rest/resource-server/src/docs/asciidoc/releases.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: REST, ready, New-UI

#2061 Add missing obligation rules
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/tools/OSADLObligationConnector.java
Labels: bug

#2055 feat(rest): New endpoint create attachments
  rest/resource-server/src/docs/asciidoc/attachments.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/AttachmentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/AttachmentSpecTest.java
Labels: REST, ready, New-UI

#1938 fix(db): Data quality and reduction of storage
  scripts/migrations/056_dataReduction.py
  scripts/migrations/README.md
Labels: ready

#2053 feat(Components): Added a new field called VCS/Repository URL for components
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/editBasicInfo.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/summary.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  libraries/datahandler/src/main/thrift/components.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
Labels: enhancement, ready
