Repository eclipse-sw360/sw360, pull requests merged in 2023-10, with the labels that each got.

#2129 feat(release): Fix response api get single release with cotsDetails
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: ready

#2101 feat(rest):Update API Create Release with Cots Detail
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: ready

#2106 fix(rest): New endpoint to download license archive files in admin page
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/LicsExporter.java
  rest/pom.xml
  rest/resource-server/src/docs/asciidoc/licenses.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
Labels: ready, New-UI

#2014 feat(rest): API to get vulnerability tracking status
  rest/resource-server/src/docs/asciidoc/vulnerabilities.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/Sw360VulnerabilityService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VulnerabilitySpecTest.java
Labels: REST, ready, New-UI

#2130 feat(rest) : End point for export vendor spreadsheet
  backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorDatabaseHandler.java
  backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorHandler.java
  libraries/datahandler/src/main/thrift/vendors.thrift
  rest/resource-server/src/docs/asciidoc/vendors.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/Sw360VendorService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VendorSpecTest.java
Labels: ready

#2001 fix(db): clean-up closed moderation requests.
  scripts/migrations/057_closedModReqStats.py
  scripts/migrations/058_deleteClosedModReq.py
  scripts/migrations/README.md
Labels: ready

#2057 New endpoint allow load assessment summary information of release (New Frontend)
  rest/resource-server/src/docs/asciidoc/releases.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: REST, ready, New-UI

#2140 feat(bug) : Releases attachment download issue fix
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: ready

#2138 fix(importCDX): Resolved unnecessary update of component fields
  backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
Labels: ready

#2134 fix(Package): Can't create a new Package by API
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/PackageSpecTest.java
Labels: REST, ready

#2123 fix(rest): Added new rest endpoint for upload license in admin tab.
  rest/pom.xml
  rest/resource-server/src/docs/asciidoc/licenses.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
Labels: ready

#2114 fix(rest): create new endpoint for import OSADL information in admin.
  rest/resource-server/src/docs/asciidoc/licenses.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
Labels: REST, ready, New-UI

#2149 feat(Rest): Modifying the document for search endpoint
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/SearchSpecTest.java
Labels: needs code review

#2096 fix(rest) : Modifications to improve API GET result speed for name search
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
Labels: enhancement, REST, ready

#2150 fix(package): Create package by API can't link release
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/PackageSpecTest.java
Labels: REST, ready

#2152 fix(UI) : Fix upload license file in admin tab.
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/utils/ConvertRecord.java
Labels: ready

#2163 fix(package): Can't link project to package by API
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Labels: needs code review, needs general test, REST

#2156 fix(REST):GET Component endpoint failing for names with space
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
Labels: REST, ready

#2143 feat(CreateCRandRequestsPortlet):Added new field Clearing Type for CR and Additional columns in Open CR table
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortletUtils.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/css/components/_tooltips.scss
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/clearing/clearingRequest.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingRequest.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  frontend/sw360-portlet/src/main/resources/content/Language_zh.properties
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
  libraries/datahandler/src/main/thrift/projects.thrift
  libraries/datahandler/src/main/thrift/sw360.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
Labels: ready

#2154 feat(importCDX): enhanced sw360 CDX importer
  backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentRepository.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/PackageDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/PackageRepository.java
Labels: ready
