Repository eclipse-sw360/sw360, pull requests merged in 2023-03, with the labels that each got.

#1824 feat(rest): new endpoint `/projects/myprojects`
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready

#1867 fix(vulnerability): apache commons-text vulnerability CVE-2022-42889 …
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTools.java
  pom.xml
Labels: needs general test

#1847 feat(rest): new endpoint /components/recentComponents
  rest/resource-server/src/docs/asciidoc/components.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
Labels: REST, ready, New-UI

#1853 feat(rest): new endpoint /releases/recentReleases
  rest/resource-server/src/docs/asciidoc/releases.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: REST, ready, New-UI

#1817 fix(db): Deactivate email notification of user not belonging to a domain
  scripts/migrations/055_deactivateEmailNotification.py
  scripts/migrations/README.md
Labels: in progress

#1852 fix(rest): Added endpoint for mysubscriptions for component
  rest/resource-server/src/docs/asciidoc/components.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
Labels: REST, ready, New-UI

#1873 fix(language): Fix the properties file and add some other needed files for Chinese language support
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/homepage/welcome/view.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/images/cn.png
  frontend/sw360-portlet/src/main/resources/content/Language_zh.properties
Labels: ready

#1780 Fix(Project): Can't disable CR based on Japanese group
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
Labels: ready

#1660 fix(rest): disable URI decoding in search by external ids in release
  clients/client/src/main/java/org/eclipse/sw360/clients/rest/SW360Client.java
  clients/client/src/main/java/org/eclipse/sw360/clients/rest/SW360ReleaseClient.java
  clients/client/src/test/java/org/eclipse/sw360/clients/rest/AbstractMockServerTest.java
  clients/client/src/test/java/org/eclipse/sw360/clients/rest/SW360ReleaseClientIT.java
  clients/http-support/src/main/java/org/eclipse/sw360/http/HttpClientFactory.java
  clients/http-support/src/main/java/org/eclipse/sw360/http/HttpClientFactoryImpl.java
  clients/http-support/src/main/java/org/eclipse/sw360/http/NewHttpClientImpl.java
  clients/http-support/src/main/java/org/eclipse/sw360/http/NewRequestBodyBuilderImpl.java
  clients/http-support/src/main/java/org/eclipse/sw360/http/NewRequestBuilderImpl.java
  clients/http-support/src/main/java/org/eclipse/sw360/http/NewResponseImpl.java
  clients/http-support/src/main/java/org/eclipse/sw360/http/utils/HttpUtils.java
  rest/resource-server/src/docs/asciidoc/releases.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: ready

#1884 Update pre-commit and ci hooks
  .github/workflows/build_and_test.yml
  .pre-commit-config.yaml
Labels: ready

#1862 feat(rest) : Update data without moderation request And This features' configurable setting
  .github/workflows/build_and_test.yml
  backend/src-common/src/main/java/org/eclipse/sw360/common/utils/BackendUtils.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src-common/src/test/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandlerTest.java
  backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
  backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
  backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
  frontend/sw360-portlet/src/main/resources/sw360.properties
  libraries/datahandler/src/main/thrift/components.thrift
  libraries/datahandler/src/main/thrift/projects.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
Labels: REST, ready

#1887 fix(UI): Attachments tab not loading in UI
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/editAttachments.jspf
Labels: ready

#1879 fix(rest): componentType field will show when allDetails true in rel…
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
Labels: ready
