Repository eclipse-sw360/sw360, pull requests merged in 2023-09, with the labels that each got.

#1648 feat(ui):Admin users can do bulk delete component/releases
  .github/workflows/build_and_test.yml
  backend/src-common/src/main/java/org/eclipse/sw360/common/utils/BackendUtils.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/BulkDeleteUtil.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/resources/sw360.properties
  backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
  backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/BulkDeleteUtilTest.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/deleteBulkRelease.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/deleteBulkReleasePreview.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/clearingStatus.jspf
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/detailOverview.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  frontend/sw360-portlet/src/main/resources/sw360.properties
  libraries/datahandler/src/main/thrift/components.thrift
Labels: ready

#2110 fix(rest): create new endpoint for import spdx information in admin tab
  rest/resource-server/src/docs/asciidoc/licenses.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
Labels: ready, New-UI

#2107 feat(REST): Add restricted project counter for component and release usedBy API
  libraries/datahandler/src/main/thrift/sw360.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: REST, ready, New-UI

#2120 fix(OAuthClient): Fix Can't show OAuth Client page
  frontend/configuration/Private_Pages_7_4_3_18_GA18.lar
Labels: needs general test

#2128 feat(docker): Add option to specify cvesearch.host at build time
  README_DOCKER.md
  docker_build.sh
Labels: enhancement, WIP, needs code review, needs general test
