Repository eclipse-sw360/sw360, pull requests merged in 2023-04, with the labels that each got.

#1858 fix(UserSearch) : Modified the user search operation
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/UserSearchHandler.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/utils/includes/searchAndSelectIds.js
  libraries/datahandler/pom.xml
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
Labels: ready

#1881 feat(rest) : endpoint for linked projects
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready, New-UI

#1574 Feat(Release): GET VULNERABILITIES from Release by API #1571
  rest/resource-server/src/docs/asciidoc/releases.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: REST, ready

#1898 feat(ProjectUI):ExternalIds and Additional Data fields in Export Excel in License Clearing
  libraries/datahandler/src/main/thrift/projects.thrift
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectExporter.java
Labels: ready

#1896 feat(EditCR): Admin will be able to reassign/edit the Requesting User of CR
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortletUtils.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/clearing/clearingRequest.jsp
Labels: ready

#1877 fix(api): Deleting a project returns status code 500 and the API doc for linking a release to a release makes an ambiguous
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: ready

#1828 fix(Script): Modified script such that it removes trailing and leading whitespaces and additonally link releases of duplicate components
  scripts/migrations/053_remove_whitespace_component_name.py
Labels: needs code review

#1773 Fix(Component UI): Can not load component detail page with long text of additional data
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/components/includes/releases/regexjs.js
Labels: ready

#1875 Fix(rest): endpoint for projects does not return all projects with allDetails=true
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Labels: ready

#1900 feat(rest): optimize fetch project
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceListController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ProjectTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready

#1934 fix(rest): added endpoint for release subscriptions
  rest/resource-server/src/docs/asciidoc/releases.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: REST, ready, New-UI

#1856 feat(rest):New end point for my components
  rest/resource-server/src/docs/asciidoc/components.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
Labels: REST, ready, New-UI

#1945 Update thrift version to 0.18.1
  .versions
Labels: dependencies
