Repository eclipse-sw360/sw360, pull requests merged in 2024-05, with the labels that each got.

#2398 feat(project): Added release field & pageable for licenseObligation endpoint
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready, New-UI

#2223 feat(rest): Create a new endpoint for database Sanitation.
  rest/resource-server/src/docs/asciidoc/api-guide.adoc
  rest/resource-server/src/docs/asciidoc/databaseSanitation.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/databasesanitation/DatabaseSanitationController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/databasesanitation/Sw360DatabaseSanitationService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ApiSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/DatabaseSanitationSpecTest.java
Labels: ready, New-UI

#2266 feat(license): Update Whitelist for License
  rest/resource-server/src/docs/asciidoc/licenses.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
Labels: REST, ready, New-UI

#2375 feat(CR): Add a new Clearing Request state PENDING INPUT
  frontend/sw360-portlet/src/main/resources/META-INF/resources/css/components/_tooltips.scss
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  frontend/sw360-portlet/src/main/resources/content/Language_zh.properties
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
  libraries/datahandler/src/main/thrift/sw360.thrift
Labels: ready

#2358 feat(rest): filter releases for attachment usages page in project
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready, New-UI

#2293 feat(REST):Create clearing request for a project
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/Sw360ModerationRequestService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: REST, ready, New-UI

#2424 feat(moderation): ignore common fields
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/ModerationRequestController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ModerationRequestSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: REST, ready, New-UI

#2446 fix(api): throw 409 if last moderator
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/Sw360ModerationRequestService.java
Labels: ready, New-UI

#2448 feat(REST): Search package by purl and version
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/PackageDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/PackageRepository.java
  backend/src/src-packages/src/main/java/org/eclipse/sw360/packages/PackageHandler.java
  libraries/datahandler/src/main/thrift/package.thrift
  rest/resource-server/src/docs/asciidoc/packages.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/packages/PackageController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/packages/SW360PackageService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/PackageSpecTest.java
Labels: REST, ready, New-UI

#2436 fix(importCDX) : Fix package's linked release updation when an SBOM is imported
  backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
Labels: ready

#2260 feat(rest) : Remove mail-request parameter and read from config file while downloading reports.
  backend/src-common/src/main/resources/sw360.properties
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
  rest/resource-server/src/docs/asciidoc/components.adoc
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/ResourceServerConfiguration.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: REST, ready, New-UI

#2257 chore(rel-18.1): changing files for tagging 18.1
  CHANGELOG.md
  pom.xml
Labels: needs code review
