Repository eclipse-sw360/sw360, pull requests merged in 2024-01, with the labels that each got.

#2234 feat(license): Listing obligations by license
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/LicenseHandler.java
  backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
  libraries/datahandler/src/main/thrift/licenses.thrift
  rest/resource-server/src/docs/asciidoc/licenses.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
Labels: REST, ready, New-UI

#2238 feat(rest): Create new endpoint to cancel all scheduled services.
  rest/resource-server/src/docs/asciidoc/api-guide.adoc
  rest/resource-server/src/docs/asciidoc/schedule.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/ScheduleAdminController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/Sw360ScheduleService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ApiSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ScheduleSpecTest.java
Labels: ready

#2218 fix(importCDX): Update failed component creation error message
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
Labels: ready

#2258 feat(User): Add new endpoints to get/update requesting user profile
  rest/resource-server/src/docs/asciidoc/users.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/Sw360UserService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java
Labels: REST, ready, New-UI

#2262 fix(package): Fix issues API for package
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/PackageDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/packages/SW360PackageService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: ready

#2255 feat(license): Fix Update License when checked field is false
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
Labels: REST, ready

#2288 fix(docker): We have been using wrong Java version
  .versions
Labels: bug, priority

#2263 feat(CR): Disable Clearing Request creation for the projects which have linked releases without SRC type attachment
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  frontend/sw360-portlet/src/main/resources/content/Language_zh.properties
Labels: ready

#2261 fix(rest): error handling when user dont have sufficient import permission
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Labels: ready

#2290 fix(release): modify the externalId query parsing
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
Labels: ready

#2286 chore(package-portlet): package-portlet enabled for default installation
  frontend/sw360-portlet/src/main/resources/sw360.properties
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
Labels: ready

#2253 feat(Project): Extract license and Download source code bundle from all releases in dependency network
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/LinkedReleasesAndProjectsAwarePortlet.java
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
  libraries/datahandler/src/main/thrift/projects.thrift
Labels: ready
