Repository eclipse-sw360/sw360, pull requests merged in 2024-10, with the labels that each got.

#2637 chore(nouveau): catch exception for nouveau query
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/NouveauLuceneAwareDatabaseConnector.java
  libraries/nouveau-handler/src/main/java/org/eclipse/sw360/nouveau/LuceneAwareCouchDbConnector.java
Labels: needs code review, needs special test

#2634 fix(UI): Add lang attribute to ReadmeOSS.html for generated license info
  backend/licenseinfo/src/main/resources/xhtmlLicenseInfoFile.vm
Labels: ready

#2599 feat(keycloak-spis): Added the custom keycloak SPIs
  keycloak/README.md
  keycloak/event-listeners/pom.xml
  keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/listener/Sw360CustomEventListenerProvider.java
  keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/listener/Sw360CustomEventListenerProviderFactory.java
  keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/listener/service/Sw360KeycloakAdminEventService.java
  keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/listener/service/Sw360KeycloakUserEventService.java
  keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/listener/service/Sw360UserService.java
  keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/model/Access.java
  keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/model/Attribute.java
  keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/model/Group.java
  keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/model/UserEntity.java
  keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/model/UserProfileMetadata.java
  keycloak/event-listeners/src/main/resources/META-INF/services/org.keycloak.events.EventListenerProviderFactory
  keycloak/pom.xml
  keycloak/register.ftl
  keycloak/user-storage-provider/pom.xml
  keycloak/user-storage-provider/src/main/java/org/eclipse/sw360/keycloak/spi/Sw360UserStorageProvider.java
  keycloak/user-storage-provider/src/main/java/org/eclipse/sw360/keycloak/spi/Sw360UserStorageProviderFactory.java
  keycloak/user-storage-provider/src/main/java/org/eclipse/sw360/keycloak/spi/model/UserAdapter.java
  keycloak/user-storage-provider/src/main/java/org/eclipse/sw360/keycloak/spi/model/UserEntity.java
  keycloak/user-storage-provider/src/main/java/org/eclipse/sw360/keycloak/spi/service/Sw360UserService.java
  keycloak/user-storage-provider/src/main/resources/META-INF/services/org.keycloak.storage.UserStorageProviderFactory
  pom.xml
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/jwt/Sw360JWTAccessTokenConverter.java
  rest/rest-common/pom.xml
Labels: ready

#2644 fix(servlet): complete migration javax to jakarta
  backend/common/pom.xml
  backend/common/src/main/java/org/eclipse/sw360/mail/MailUtil.java
  backend/components/src/main/java/org/eclipse/sw360/components/ComponentServlet.java
  backend/fossology/src/main/java/org/eclipse/sw360/fossology/rest/FossologyRestClient.java
  backend/pom.xml
  backend/projects/src/main/java/org/eclipse/sw360/projects/ProjectServlet.java
  clients/client/pom.xml
  clients/http-support/pom.xml
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseConnectorCloudant.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseRepositoryCloudantClient.java
  pom.xml
  rest/authorization-server/pom.xml
  rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/customheaderauth/Sw360CustomHeaderAuthenticationFilter.java
  rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/customheaderauth/Sw360CustomHeaderAuthenticationProvider.java
  rest/resource-server/pom.xml
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/databasesanitation/Sw360DatabaseSanitationService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/Sw360VendorService.java
Labels: needs code review, needs general test

#2470 feat(rest): Create a new rest api to fetch group list in project add and edit page.
  rest/resource-server/src/docs/asciidoc/users.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java
Labels: ready

#2483 feat(ImportSBOM):Change naming convention of imported components
  backend/common/src/main/java/org/eclipse/sw360/components/summary/ComponentSummary.java
  backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/PackageDatabaseHandler.java
Labels: ready

#2606 feat(rest): endpoint to update a vendor.
  backend/vendors/src/main/java/org/eclipse/sw360/vendors/VendorDatabaseHandler.java
  rest/resource-server/src/docs/asciidoc/vendors.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/Sw360VendorService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VendorSpecTest.java
Labels: ready

#2612 feat(Project): Create new endpoint to serve list view of dependency network (New GUI)
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  libraries/datahandler/src/main/thrift/projects.thrift
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: REST, ready, New-UI

#2633 fix(REST): Patch Release is causing the clearing state to be updated to NEW even if a Clearing is existing
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
Labels: REST, ready

#2496 feat(REST): Exclude release version from license info
  backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
  backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/JsonGenerator.java
  backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/OutputGenerator.java
  backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/TextGenerator.java
  backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGenerator.java
  backend/licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGeneratorTest.java
  libraries/datahandler/src/main/thrift/licenseinfo.thrift
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/licenseinfo/Sw360LicenseInfoService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready

#2442 fix(rest) : Move GenerateLicenseInfoFile rest end point to SW360reportcontroller
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready

#2648 fix(build): add the missing excludeReleaseVersion
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: needs code review

#2614 feat(Project): Add new endpoint for project's license clearing tree view
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
  libraries/datahandler/src/main/thrift/projects.thrift
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: REST, ready, New-UI

#2361 fix(Project): Import SPDX as dependency network
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/common/src/main/java/org/eclipse/sw360/spdx/SpdxBOMImporter.java
  backend/common/src/test/java/org/eclipse/sw360/spdx/SpdxBOMImporterTest.java
Labels: ready

#2278 feat(rest): Create new endpoint to download component template, attachment template, attachment information and release link sample in csv format.
  rest/resource-server/src/docs/asciidoc/api-guide.adoc
  rest/resource-server/src/docs/asciidoc/importExport.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/ImportExportController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ApiSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ImportExportSpecTest.java
Labels: ready, New-UI

#2372 feat(rest): saveUsages in project page
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: REST, ready, New-UI

#2340 feat(rest) : Rest end point for generate source code bundle
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: needs general test, New-UI

#2545 fix(clearingState): making fossology report download configurable.
  backend/common/src/main/java/org/eclipse/sw360/common/utils/BackendUtils.java
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/common/src/main/resources/sw360.properties
  backend/fossology/src/main/java/org/eclipse/sw360/fossology/FossologyHandler.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/PermissionUtils.java
Labels: ready

#2564 feat(rest): get releases used by vendor
  rest/resource-server/src/docs/asciidoc/vendors.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/Sw360VendorService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VendorSpecTest.java
Labels: ready

#2243 feat(rest): Create new endpoint for schedule CVE and schedule attachment deletion in admin tab.
  rest/resource-server/src/docs/asciidoc/schedule.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/ScheduleAdminController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/Sw360ScheduleService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ScheduleSpecTest.java
Labels: ready, New-UI

#2549 feat(rest): Endpoint to add comment on a clearing request.
  rest/resource-server/src/docs/asciidoc/clearingRequests.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/ClearingRequestController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/Sw360ClearingRequestService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ClearingRequestSpecTest.java
Labels: ready

#2636 Fix bug: Project test fail when enable.flexible.project.release.relationship=true
  backend/common/src/test/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandlerTest.java
  backend/components/src/test/java/org/eclipse/sw360/components/db/ProjectDatabaseHandlerTest.java
Labels: ready

#2635 fix(ImportCDX): VCS sanitization failing on characters like colon
  backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
Labels: ready

#2638 fix(cloudant): fix attachment creation
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentDatabaseHandler.java
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/components/src/test/java/org/eclipse/sw360/components/db/BulkDeleteUtilTest.java
  backend/fossology/src/main/java/org/eclipse/sw360/fossology/config/FossologyRestConfig.java
  backend/licenses-core/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
  backend/licenses/src/test/java/org/eclipse/sw360/licenses/LicenseHandlerTest.java
  backend/moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
  backend/moderation/src/test/java/org/eclipse/sw360/moderation/testutil/DatabaseTestSetup.java
  backend/utils/src/test/java/org/eclipse/sw360/attachments/db/RemoteAttachmentDownloaderTest.java
  backend/vendors/src/main/java/org/eclipse/sw360/vendors/VendorDatabaseHandler.java
  backend/vendors/src/test/java/org/eclipse/sw360/vendors/TestVendorClient.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseConnectorCloudant.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseRepositoryCloudantClient.java
  libraries/importers/src/test/java/org/eclipse/sw360/importer/ComponentImportUtilsTest.java
  rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/client/rest/OAuthClientController.java
  rest/authorization-server/src/test/java/org/eclipse/sw360/rest/authserver/client/persistence/OAuthClientRepositoryTest.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Labels: needs general test

#2656 chore(rel-19.0): changing files for tagging 19.0
  .versions
  CHANGELOG.md
  backend/attachments/pom.xml
  backend/changelogs/pom.xml
  backend/common/pom.xml
  backend/components/pom.xml
  backend/cvesearch/pom.xml
  backend/fossology/pom.xml
  backend/health/pom.xml
  backend/licenseinfo/pom.xml
  backend/licenses-core/pom.xml
  backend/licenses/pom.xml
  backend/moderation/pom.xml
  backend/packages/pom.xml
  backend/pom.xml
  backend/projects/pom.xml
  backend/schedule/pom.xml
  backend/search/pom.xml
  backend/service-core/pom.xml
  backend/spdxdocument/pom.xml
  backend/spdxdocumentcreationinfo/pom.xml
  backend/spdxpackageinfo/pom.xml
  backend/users/pom.xml
  backend/utils/pom.xml
  backend/vendors/pom.xml
  backend/vmcomponents/pom.xml
  backend/vulnerabilities-core/pom.xml
  backend/vulnerabilities/pom.xml
  backend/wsimport/pom.xml
  build-configuration/pom.xml
  clients/client/pom.xml
  clients/http-support/pom.xml
  clients/pom.xml
  keycloak/README.md
  keycloak/event-listeners/pom.xml
  keycloak/pom.xml
  keycloak/user-storage-provider/pom.xml
  libraries/commonIO/pom.xml
  libraries/datahandler/pom.xml
  libraries/exporters/pom.xml
  libraries/importers/pom.xml
  libraries/log4j-osgi-support/pom.xml
  libraries/nouveau-handler/pom.xml
  libraries/pom.xml
  pom.xml
  rest/authorization-server/pom.xml
  rest/pom.xml
  rest/resource-server/pom.xml
  rest/rest-common/pom.xml
  utils/pom.xml
Labels: needs code review
