Repository eclipse-sw360/sw360, pull requests merged in 2024-12, with the labels that each got.

#2749 feat(Import CDX): Handle redirection of VCS URLs in SBOM
  backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
Labels: needs general test

#2788 feat(FossologyTrigger): stop repetitive entries of attachment.
  backend/fossology/src/main/java/org/eclipse/sw360/fossology/FossologyHandler.java
  backend/fossology/src/main/java/org/eclipse/sw360/fossology/rest/FossologyRestClient.java
Labels: ready

#2738 feat(Release): Add new endpoint for release subscription
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: REST, ready, New-UI

#2737 feat(Component): Add new endpoint that allows user to subscribe and unsubscribe to a component
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
Labels: REST, ready, New-UI

#2471 feat(rest) : Rest end point for project ECC Export Spreadsheet
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready

#2754 feat(rest): Add documentation for new clearing size parameter.
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ClearingRequestSpecTest.java
Labels: ready

#2779 feat(rest): endpoint to get license info header text.
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: needs code review

#2482 Revert "fix(importCDX): Resolved unnecessary update of component fields"
  backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
Labels: ready

#2493 feat(rest) : Export Project Create Clearing Request
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready

#2709 fix(openapi)!: add health endpoint to openapi
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/ResourceServerConfiguration.java
  rest/resource-server/src/main/resources/application.yml
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/SW360RestHealthIndicatorTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/configuration/security/Sw360AuthorizationServerConfiguration.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/HealthSpecTest.java
  rest/resource-server/src/test/resources/application.yml
Labels: REST, ready, breaking change

#2813 chore(release): tag release 19.1.0
  CHANGELOG.md
  backend/attachments/pom.xml
  backend/changelogs/pom.xml
  backend/common/pom.xml
  backend/components/pom.xml
  backend/cvesearch/pom.xml
  backend/fossology/pom.xml
  backend/health/pom.xml
  backend/licenseinfo/pom.xml
  backend/licenses-core/pom.xml
  backend/licenses/pom.xml
  backend/moderation/pom.xml
  backend/packages/pom.xml
  backend/pom.xml
  backend/projects/pom.xml
  backend/schedule/pom.xml
  backend/search/pom.xml
  backend/service-core/pom.xml
  backend/spdxdocument/pom.xml
  backend/spdxdocumentcreationinfo/pom.xml
  backend/spdxpackageinfo/pom.xml
  backend/users/pom.xml
  backend/utils/pom.xml
  backend/vendors/pom.xml
  backend/vmcomponents/pom.xml
  backend/vulnerabilities-core/pom.xml
  backend/vulnerabilities/pom.xml
  backend/wsimport/pom.xml
  build-configuration/pom.xml
  clients/client/pom.xml
  clients/http-support/pom.xml
  clients/pom.xml
  keycloak/event-listeners/pom.xml
  keycloak/pom.xml
  keycloak/user-storage-provider/pom.xml
  libraries/commonIO/pom.xml
  libraries/datahandler/pom.xml
  libraries/exporters/pom.xml
  libraries/importers/pom.xml
  libraries/nouveau-handler/pom.xml
  libraries/pom.xml
  pom.xml
  rest/authorization-server/pom.xml
  rest/pom.xml
  rest/resource-server/pom.xml
  rest/rest-common/pom.xml
  utils/pom.xml
Labels: ready

#2492 fix(rest): Added code for updating multiple project attachments.
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/TestRestDocsSpecBase.java
Labels: ready

#2498 fix(rest) : modified attachment info in response to the moderation request rest api
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/ModerationRequestController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ModerationRequestSpecTest.java
Labels: ready

#2820 fix(moderation): fix moderation creation
  backend/moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseConnectorCloudant.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
Labels: ready

#2831 fix(cloudant): fix structure of elemMatch query
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseConnectorCloudant.java
Labels: ready

#2750 fix(deps): Deprecate old commmons-lang library
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  backend/fossology/src/main/java/org/eclipse/sw360/fossology/FossologyHandler.java
  backend/fossology/src/main/java/org/eclipse/sw360/fossology/rest/FossologyRestClient.java
  backend/licenseinfo/pom.xml
  backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
  backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxUtils.java
  backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGenerator.java
  backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/AbstractCLIParser.java
  backend/search/src/main/java/org/eclipse/sw360/search/db/SearchDocument.java
  backend/vmcomponents/src/main/java/org/eclipse/sw360/vmcomponents/VMComponentHandler.java
  backend/vmcomponents/src/main/java/org/eclipse/sw360/vmcomponents/common/SVMMapper.java
  backend/vmcomponents/src/main/java/org/eclipse/sw360/vmcomponents/db/VMDatabaseHandler.java
  backend/vmcomponents/src/main/java/org/eclipse/sw360/vmcomponents/handler/SVMSyncHandler.java
  backend/vmcomponents/src/main/java/org/eclipse/sw360/vmcomponents/process/VMProcessHandler.java
  backend/vmcomponents/src/test/java/org/eclipse/sw360/vmcomponents/handler/SVMSyncHandlerTest.java
  backend/vulnerabilities-core/src/main/java/org/eclipse/sw360/vulnerabilities/db/VulnerabilityDatabaseHandler.java
  backend/vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/VulnerabilityHandler.java
  libraries/datahandler/src/test/java/org/eclipse/sw360/datahandler/permissions/DocumentPermissionsTest.java
  libraries/nouveau-handler/pom.xml
  pom.xml
  rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/client/rest/OAuthClientController.java
  rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/Sw360UserDetailsProvider.java
  rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/customheaderauth/Sw360CustomHeaderAuthenticationFilter.java
  rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/customheaderauth/Sw360CustomHeaderAuthenticationProvider.java
  rest/resource-server/pom.xml
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
Labels: needs code review, ready

#2764 fix(rest): adding additional fields to attachmentUsage endpoint.
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Labels: ready
