Repository eclipse-sw360/sw360, pull requests merged in 2024-04, with the labels that each got.

#2246 Feat(User): Create new endpoints to Create/Revoke/List rest API token for users
  rest/resource-server/src/docs/asciidoc/users.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/Sw360UserService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java
Labels: REST, ready, New-UI

#2380 fix(Release): Add embedded other licenses in release response
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: REST, ready, New-UI

#2391 fix(Project): Fix bug Expand Next Level and Collapse All button are hidden when click on sort icon
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/dependencyNetwork.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/expandCollapse.js
Labels: ready

#2401 fix(api): check project modifier before embedding
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Labels: REST, ready

#2221 fix(importCDX): Resolve duplicate release creation during SBOM import
  backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
Labels: ready

#2403 fix(api): provide typeMasks name as Optional type
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/search/SearchController.java
Labels: REST, ready, New-UI

#2388 fix(importCDX): Packages without VCS in SBOM having VCS in SW360 are not getting linked to project
  backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/attachmentsDetail.jsp
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/importBom.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  frontend/sw360-portlet/src/main/resources/content/Language_zh.properties
Labels: ready

#2389 fix(importCDX): Add check for existing comps and package using case-insensitive comparison of vcs and purl
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentRepository.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/PackageDatabaseHandler.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/PackageRepository.java
Labels: ready

#2378 fix(SRCUploadService): Source upload should work for release versions having alphanumeric characters
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
Labels: ready

#2413 fix(Release): Updating the license overview in the summary page
  frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
Labels: ready

#2385 fix(rest): url decoding.
  rest/resource-server/src/docs/asciidoc/components.adoc
  rest/resource-server/src/docs/asciidoc/packages.adoc
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/docs/asciidoc/releases.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/packages/PackageController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: REST, breaking change

#2423 fix(sw360): changing mkdocs version
  .github/workflows/build_and_test.yml
Labels: ready

#2414 fix(REST): Improve error message handling for CycloneDX sbom import using REST API
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Labels: ready

#2407 feat(rest): added pagination for vulnerability tracking status page.
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VulnerabilitySpecTest.java
Labels: needs code review, New-UI

#2427 fix(importCDX): Resolve incorrect package/release count in import summary
  backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
Labels: ready
