Repository eclipse-sw360/sw360, pull requests merged in 2024-09, with the labels that each got.

#2547 fix(rest): Added code to resolve the server error while fetching a summaryAdministraion endpoint.
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Labels: ready

#2517 fix(rest): modified accept request to see the proposed changes in user to moderation request rest Api.
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/Sw360ModerationRequestService.java
Labels: ready, New-UI

#2600 fix(rest): Add null check for linkedProject field
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
Labels: ready

#2488 feat(rest): includeAllAttachments parameter in licenseInfo endpoint
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTools.java
  backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTest.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready

#2570 fix(rest): Ensure visibility field is case-insensitive
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Labels: ready

#2603 feat(rest): Endpoint to get comments of a Clearing Request.
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGenerator.java
  rest/resource-server/src/docs/asciidoc/clearingRequests.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/ClearingRequestController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ClearingRequestSpecTest.java
Labels: ready

#2468 feat(api): postpone moderation request action
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/ModerationPatch.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/ModerationRequestController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/Sw360ModerationRequestService.java
Labels: REST, ready, New-UI

#2605 fix(GenerateLicenseInfo): Generate License Info is failing for releases having the same CLX
  backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
Labels: ready

#2408 feat(ComponentPortlet & ImportCDX): Validate VCS URL
  backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
  backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
Labels: ready

#2521 feat(CycloneDX): Update cyclonedx-core-java and jackson version
  backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMExporter.java
  pom.xml
Labels: ready

#2618 fix(rest): Resolved null value returning for svm tracking status.
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
Labels: ready

#2616 feat(rest): Add additional fields in get clearingrequest endpoints.
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/ClearingRequestController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ClearingRequestSpecTest.java
Labels: needs code review

#2628 chore: Reduce couchdb log level on docker compose
  config/couchdb/sw360_log.ini
  docker-compose.yml
Labels: ready
