Repository eclipse-sw360/sw360, pull requests merged in 2024-02, with the labels that each got.

#2231 feat(rest): endpoint to link sourceProject to list of projects.
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: REST, ready

#2297 feat(UI): Add clearing type column in closed clearing request tab
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
Labels: ready

#2300 fix(UI) : Issue fix for vulnerability not displaying for project
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/vulnerabilities.jsp
Labels: ready

#2283 fix(database): Restore reading environment database vars
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/DatabaseSettings.java
  libraries/datahandler/src/test/java/org/eclipse/sw360/datahandler/couchdb/DatabaseTestProperties.java
Labels: bug

#2282 feat(UI): Add an info button in the create CR page
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingRequest.jspf
  frontend/sw360-portlet/src/main/resources/content/Language.properties
  frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
  frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
  frontend/sw360-portlet/src/main/resources/content/Language_zh.properties
Labels: ready

#2279 feat(UI): enhanced date filter for open and closed clearing requests tab
  frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
Labels: ready

#2244 feat(rest) : Rest Api for ECC page
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGenerator.java
  rest/resource-server/src/docs/asciidoc/api-guide.adoc
  rest/resource-server/src/docs/asciidoc/ecc.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/ecc/EccController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ApiSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/EccSpecTest.java
Labels: ready

#2304 feat(rest) : Pagination for vulnerability tracking status
  rest/resource-server/src/docs/asciidoc/vulnerabilities.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VulnerabilitySpecTest.java
Labels: ready

#2315 fix(rest): Added modifiedBy field in project search by project id.
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
Labels: ready

#2271 feat(api): new endpoint /mySubmissions
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/ModerationHandler.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
  backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationRequestRepository.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGenerator.java
  libraries/datahandler/src/main/thrift/moderation.thrift
  rest/resource-server/src/docs/asciidoc/moderationRequests.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/ModerationRequestController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/Sw360ModerationRequestService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ModerationRequestSpecTest.java
Labels: REST, ready, New-UI

#2317 fix(script): update modifiedBy/modifiedOn project fields.
  scripts/migrations/061_add_modifiedBy_modifiedOn_project.py
  scripts/migrations/README.md
Labels: ready
