Repository eclipse-sw360/sw360, pull requests merged in 2025-08, with the labels that each got.

#3282 bug(spdx): fixed spdx import format
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
Labels: ready

#3312 Fix NPE During License Info Generation; Support Projects With and Without Linked Projects
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Labels: ready

#3334 feat(ci): use couchdb as actions service
  .github/workflows/build_and_test.yml
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/VulnerabilityTest.java
Labels: ready, github_actions

#3322 fix(sbom-import): handle invalid VCS URLs in SBOM-import
  backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
Labels: ready

#3357 fix(CDXImport): Trim VCS URLs before processing
  backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
Labels: needs general test

#3338 feat(Rest): Added comment for package table in LinkedPakages
  backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMExporter.java
  backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
  libraries/datahandler/src/main/thrift/projects.thrift
  libraries/datahandler/src/main/thrift/sw360.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
  scripts/migrations/062_update_packagIds_to_map.py
Labels: ready
