Repository eclipse-sw360/sw360, pull requests merged in 2025-02, with the labels that each got.

#2893 fix(Rest): new endpoint will help to get the package details by projectID
  rest/resource-server/src/docs/asciidoc/projects.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready

#2917 fix(Attachment): Make get attachment endpoints consistent, allow to update project/component/release with attachment data
  backend/attachments/src/main/java/org/eclipse/sw360/attachments/AttachmentHandler.java
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentDatabaseHandler.java
  libraries/datahandler/src/main/thrift/attachments.thrift
  libraries/datahandler/src/main/thrift/components.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/AttachmentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/AttachmentSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Labels: needs code review, needs general test, REST, New-UI

#2915 fix(rest) : Moderation update overwrites previous fields
  backend/moderation/src/main/java/org/eclipse/sw360/moderation/db/ProjectModerationRequestGenerator.java
Labels: ready

#2881 fix(rest) : Add licenseInfoHeaderText in summaryAdministration api response
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready

#2913 feat(User): Add 2 new endpoints for updating user and listing existing departments
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/UserRepository.java
  backend/users/src/main/java/org/eclipse/sw360/users/UserHandler.java
  backend/users/src/main/java/org/eclipse/sw360/users/db/UserDatabaseHandler.java
  libraries/datahandler/src/main/thrift/users.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/Sw360UserService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/UserTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java
Labels: REST, ready, New-UI
