Repository eclipse-sw360/sw360, pull requests merged in 2025-03, with the labels that each got.

#2870 feat(rest): endpoint to merge vendor.
  rest/resource-server/src/docs/asciidoc/vendors.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/Sw360VendorService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VendorSpecTest.java
Labels: ready, New-UI

#2923 feat(rest) : Comment added to reuse methods for Duplicateobligation functionality
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/obligation/ObligationController.java
Labels: ready

#2943 feat: Add multiarch for docker image
  .github/workflows/build_and_test.yml
  .github/workflows/docker_deploy.yml
Labels: ready

#2934 feat(rest) : Search for vendors added
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/Sw360VendorService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
Labels: needs general test

#2916 fix(Rest): Create new endpoint to activate the department manually.
  backend/users/src/main/java/org/eclipse/sw360/users/db/UserDatabaseHandler.java
  backend/users/src/main/java/org/eclipse/sw360/users/util/ReadFileDepartmentConfig.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
  rest/resource-server/src/docs/asciidoc/api-guide.adoc
  rest/resource-server/src/docs/asciidoc/department.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/department/DepartmentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/department/Sw360DepartmentService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ApiSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/DepartmentSpecTest.java
Labels: ready, New-UI

#2416 feat(rest): create new endpoint for bulk delete function
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/BulkDeleteUtil.java
  backend/components/src/test/java/org/eclipse/sw360/components/db/BulkDeleteUtilTest.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
Labels: REST, ready, New-UI

#2405 fix(rest): Added a commit message while create a moderation request.
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Labels: ready

#2961 refactor: Fix Thrift to 0.20.0 and split from main docker
  .github/testForLicenseHeaders.sh
  .github/workflows/build_and_test.yml
  .github/workflows/sw360_container.yml
  .github/workflows/thrift_container.yml
  .versions
  Dockerfile
  docker_build.sh
  sw360.code-workspace
  third-party/thrift/Dockerfile
  third-party/thrift/install-thrift.sh
  third-party/thrift/version
Labels: docker, buildsystem, refactor

#2962 fix: Adjust sw360 container build for external thrift
  .github/workflows/build_and_test.yml
  .github/workflows/sw360_container.yml
  .github/workflows/thrift_container.yml
  docker_build.sh
  pom.xml
Labels: bug

#2946 fix(project): null check at /summaryAdministration
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Labels: ready

#2976 fix(script): fix addUnsafeDefaultClient.sh script
  scripts/addUnsafeDefaultClient.sh
Labels: ready

#2975 feat(exportCDX): update CycloneDX exporter dependency from v1.4 to v1.6
  backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMExporter.java
Labels: ready

#2955 fix(SPDXDocument): Fix bug add SPDX document always return fail
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/SW360SPDXDocumentService.java
Labels: ready

#2973 fix(Token): Fix bug authentication by user token not working
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/SimpleAuthenticationEntryPoint.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/ResourceServerConfiguration.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/apiToken/ApiTokenAuthenticationFilter.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/apiToken/ApiTokenAuthenticationProvider.java
Labels: ready

#2954 refactor(rest): improve logging in FossologyRestClient
  backend/fossology/src/main/java/org/eclipse/sw360/fossology/rest/FossologyRestClient.java
Labels: ready

#2974 feat(project): add new values to project state field
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
  libraries/datahandler/src/main/thrift/projects.thrift
Labels: ready

#2998 chore(controller): fix typo in endpoint name
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/AttachmentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/HalResource.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/search/SearchController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ApiSpecTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Labels: ready

#2935 feat(rest) :New Rest end point for edit obligation
  backend/licenses-core/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/obligation/ObligationController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/obligation/Sw360ObligationService.java
Labels: ready

#2981 feat(script): read host, user and pass as args
  scripts/addUnsafeDefaultClient.sh
Labels: ready

#2996 feat(rest): Added endpoints to fetch schedule service status
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/ScheduleAdminController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/Sw360ScheduleService.java
Labels: ready

#3008 fix(project): set fields getLicenseObligationData
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
Labels: ready

#2997 feat(rest): Added tests for upload and download components
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/TestHelper.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ComponentTest.java
Labels: ready

#2984 feat(Department): Add new endpoints for the Admin Department page
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/UserRepository.java
  backend/users/src/main/java/org/eclipse/sw360/users/UserHandler.java
  backend/users/src/main/java/org/eclipse/sw360/users/db/UserDatabaseHandler.java
  backend/users/src/main/java/org/eclipse/sw360/users/util/FileUtil.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
  libraries/datahandler/src/main/thrift/users.thrift
  rest/resource-server/src/docs/asciidoc/department.adoc
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/department/DepartmentController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/department/Sw360DepartmentService.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/DepartmentSpecTest.java
Labels: REST, ready, New-UI
