Repository eclipse-sw360/sw360, pull requests merged in 2025-07, with the labels that each got.

#3243 chore(rest): paginate users endpoint on DB
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/UserRepository.java
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/UserSearchHandler.java
  backend/users/src/main/java/org/eclipse/sw360/users/UserHandler.java
  backend/users/src/main/java/org/eclipse/sw360/users/db/UserDatabaseHandler.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseConnectorCloudant.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/NouveauLuceneAwareDatabaseConnector.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGenerator.java
  libraries/datahandler/src/main/thrift/users.thrift
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/Sw360UserService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/UserTest.java
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java
Labels: ready

#3250 chore(release): 20.0.0 beta release
  CHANGELOG.md
  backend/attachments/pom.xml
  backend/changelogs/pom.xml
  backend/common/pom.xml
  backend/components/pom.xml
  backend/configurations/pom.xml
  backend/cvesearch/pom.xml
  backend/fossology/pom.xml
  backend/health/pom.xml
  backend/licenseinfo/pom.xml
  backend/licenses-core/pom.xml
  backend/licenses/pom.xml
  backend/moderation/pom.xml
  backend/packages/pom.xml
  backend/pom.xml
  backend/projects/pom.xml
  backend/schedule/pom.xml
  backend/search/pom.xml
  backend/service-core/pom.xml
  backend/spdxdocument/pom.xml
  backend/spdxdocumentcreationinfo/pom.xml
  backend/spdxpackageinfo/pom.xml
  backend/users/pom.xml
  backend/utils/pom.xml
  backend/vendors/pom.xml
  backend/vmcomponents/pom.xml
  backend/vulnerabilities-core/pom.xml
  backend/vulnerabilities/pom.xml
  backend/wsimport/pom.xml
  build-configuration/pom.xml
  clients/client/pom.xml
  clients/http-support/pom.xml
  clients/pom.xml
  keycloak/event-listeners/pom.xml
  keycloak/pom.xml
  keycloak/user-storage-provider/pom.xml
  libraries/commonIO/pom.xml
  libraries/datahandler/pom.xml
  libraries/exporters/pom.xml
  libraries/importers/pom.xml
  libraries/nouveau-handler/pom.xml
  libraries/pom.xml
  pom.xml
  rest/authorization-server/pom.xml
  rest/pom.xml
  rest/resource-server/pom.xml
  rest/rest-common/pom.xml
  utils/pom.xml
Labels: ready

#3274 docs(licenseinfo): better excp for wrong generator
  backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/licenseinfo/Sw360LicenseInfoService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
Labels: ready

#3267 test(integration): added user integration tests in UserTest
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/UserTest.java
Labels: ready

#3263 test(integration): added component integration tests in ComponentTest
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ComponentTest.java
Labels: ready, has merge conflicts

#3277 chore(datahandler): migrate deprecated APIs
  backend/common/src/main/java/org/eclipse/sw360/common/utils/RepositoryURL.java
  backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/SvmConnector.java
  backend/cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasource/CveSearchApiImpl.java
  backend/cvesearch/src/test/java/org/eclipse/sw360/cvesearch/datasource/CveSearchDataTestHelper.java
  backend/fossology/src/main/java/org/eclipse/sw360/fossology/config/FossologyRestConfig.java
  backend/fossology/src/main/java/org/eclipse/sw360/fossology/rest/FossologyRestClient.java
  backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
  backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxUtils.java
  backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTools.java
  backend/licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/TestHelper.java
  backend/licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/CLIParserTest.java
  backend/licenses-core/src/main/java/org/eclipse/sw360/licenses/tools/OSADLObligationConnector.java
  backend/utils/src/main/java/org/eclipse/sw360/UtilsEntryPoint.java
  backend/vmcomponents/src/main/java/org/eclipse/sw360/vmcomponents/common/SVMUtils.java
  backend/vmcomponents/src/main/java/org/eclipse/sw360/vmcomponents/handler/SVMSyncHandler.java
  clients/client/src/main/java/org/eclipse/sw360/clients/adapter/SW360AttachmentUtils.java
  clients/client/src/main/java/org/eclipse/sw360/clients/config/SW360ClientConfig.java
  clients/http-support/src/main/java/org/eclipse/sw360/http/NewRequestBodyBuilderImpl.java
  clients/http-support/src/main/java/org/eclipse/sw360/http/RequestBodyBuilderImpl.java
  clients/http-support/src/main/java/org/eclipse/sw360/http/utils/HttpUtils.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ImportCSV.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/AttachmentContentDownloader.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/AttachmentStreamConnector.java
  libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftClients.java
  libraries/datahandler/src/test/java/org/eclipse/sw360/datahandler/TestUtils.java
  libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ExcelExporter.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/jwt/Sw360JWTAccessTokenConverter.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/keycloak/KeycloakAccessTokenConverter.java
  rest/rest-common/src/main/java/org/eclipse/sw360/rest/common/Sw360XSSRequestWrapper.java
Labels: needs code review

#3279 fix(sbom): add support for older CycloneDX XML/JSON format
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/spdx/document/SpdxDocumentDatabaseHandler.java
Labels: ready

#3261 feat(ClearingRequest): Count all non-OSS components in the CR comments
  backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
Labels: ready

#3284 test(integration): added project integration tests in ProjectTest
  rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ProjectTest.java
Labels: ready

#3295 fix(rest) : Check vendor usage before delete
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/Sw360VendorService.java
  rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
Labels: ready
